// More careers, plus facts for every career.
// Pay, growth, and education: U.S. Bureau of Labor Statistics, Occupational Outlook Handbook
// (median annual pay, May 2025; projected employment growth 2025-2035).
// `usn` = rank in U.S. News & World Report's 2026 Best Jobs (only ranks we could confirm are listed).
(function () {
  const D = window.PF_DATA;

  D.CATEGORIES = [
    { id: 'all', label: 'All' },
    { id: 'health', label: '🩺 Health' },
    { id: 'tech', label: '💻 Tech' },
    { id: 'business', label: '💼 Business' },
    { id: 'build', label: '🔧 Engineering & trades' },
    { id: 'creative', label: '🎨 Creative & media' },
    { id: 'science', label: '🔬 Science' },
    { id: 'people', label: '🍎 Education, law & people' },
  ];

  // Facts + "what you'd do" for the careers that already existed.
  const META = {
    'data-scientist': { cat: 'tech', pay: 120230, growth: 35, edu: "Bachelor's degree", usn: 8, does: ['Collect and clean data from apps, sensors, or surveys', 'Build charts and models that predict what happens next', 'Explain findings to people who make decisions'] },
    'software-engineer': { cat: 'tech', pay: 134040, growth: 10, edu: "Bachelor's degree", usn: 7, does: ['Design and write the code behind apps, games, and websites', 'Find and fix bugs with a team', 'Test that software is fast, safe, and easy to use'] },
    'physician': { cat: 'health', pay: 275930, growth: 4, edu: 'Medical degree (MD or DO) after college', does: ['Examine patients and figure out what is wrong', 'Plan treatments and explain them clearly', 'Work with nurses, specialists, and families'] },
    'mech-engineer': { cat: 'build', pay: 104110, growth: 11, edu: "Bachelor's degree", does: ['Design machines like engines, robots, and medical devices', 'Test prototypes and improve them', 'Use math and physics to make things work safely'] },
    'graphic-designer': { cat: 'creative', pay: 62960, growth: -2, edu: "Bachelor's degree", does: ['Create logos, posters, apps, and packaging', 'Choose colors, fonts, and layouts that communicate clearly', 'Turn a client\'s idea into a finished design'] },
    'teacher': { cat: 'people', pay: 72040, growth: 0, edu: "Bachelor's degree + teaching license", does: ['Plan lessons that make ideas click', 'Help each student find the way they learn best', 'Cheer on students and guide them through hard moments'] },
    'entrepreneur': { cat: 'business', pay: null, growth: null, edu: 'No set path (many start while still in school)', does: ['Spot a problem and build a product or service to solve it', 'Find customers, make a budget, and keep going when it is hard', 'Lead a team (even if the team starts as just you)'] },
    'lawyer': { cat: 'people', pay: 159670, growth: 5, edu: 'Law degree (JD) after college', does: ['Research laws and build strong arguments', 'Advise people and organizations on their rights', 'Speak for clients in negotiations and courtrooms'] },
    'psychologist': { cat: 'people', pay: 99110, growth: 6, edu: "Master's or doctoral degree", usn: 57, does: ['Study how people think, feel, and behave', 'Help people work through stress, fears, and challenges', 'Run research and use statistics to learn what works'] },
    'env-scientist': { cat: 'science', pay: 82220, growth: 6, edu: "Bachelor's degree", does: ['Collect air, water, and soil samples in the field', 'Analyze data to find pollution or other risks', 'Advise governments and companies on protecting nature'] },
    'financial-analyst': { cat: 'business', pay: 103570, growth: 7, edu: "Bachelor's degree", does: ['Study companies and markets with data', 'Recommend where money should be invested', 'Build spreadsheets and models that forecast results'] },
    'journalist': { cat: 'creative', pay: 62200, growth: -6, edu: "Bachelor's degree", does: ['Find stories and interview people', 'Check facts before anything is published', 'Write, film, or record the news for readers and viewers'] },
    'architect': { cat: 'build', pay: 99280, growth: 4, edu: "Bachelor's degree in architecture", does: ['Design buildings that are beautiful, safe, and useful', 'Draw plans and 3D models', 'Work with builders and clients to bring the plan to life'] },
    'nurse': { cat: 'health', pay: 97550, growth: 6, edu: "Bachelor's degree (or associate's degree)", does: ['Care for patients, check their health, and give treatments', 'Teach patients and families how to stay well', 'Stay calm and make quick decisions in busy moments'] },
  };
  D.CAREERS.forEach((c) => Object.assign(c, META[c.id] || {}));

  const path = (ms, g9, g10, g11, g12) => ({ ms, 9: g9, 10: g10, 11: g11, 12: g12 });

  const EXTRA = [
    { id: 'nurse-practitioner', title: 'Nurse Practitioner', emoji: '👩‍⚕️', cat: 'health', pay: 134920, growth: 41, edu: "Master's degree (after nursing)", usn: 1,
      summary: 'An advanced nurse who diagnoses, treats, and prescribes, often as a patient\'s main health provider. Ranked the #1 job in the U.S. three years running.',
      does: ['Examine patients, order tests, and diagnose illnesses', 'Prescribe medicine and create treatment plans', 'Teach people how to stay healthy'],
      traits: { S: 3, I: 2, C: 1 }, subjects: ['Biology', 'Chemistry', 'Psychology'],
      keywords: ['nurse', 'nursing', 'medicine', 'health', 'helping', 'hospital', 'doctor', 'caring', 'biology', 'first aid'],
      skills: ['Biology & chemistry', 'Communication & empathy', 'Clinical reasoning', 'Staying calm under pressure'], domains: ['science', 'people', 'stats'],
      path: path(['Take strong science and math classes', 'Learn first aid and CPR', 'Volunteer to help people (hospital, senior center)'], ['Honors Biology', 'Join HOSA – Future Health Professionals', 'Volunteer in a health setting'], ['Honors Chemistry', 'CPR certification', 'Shadow a nurse or nurse practitioner'], ['AP Biology or Anatomy & Physiology', 'AP Statistics or Psychology', 'Certified Nursing Assistant (CNA) course if offered'], ['Apply to Bachelor of Science in Nursing (BSN) programs', 'Work or volunteer in healthcare this summer']),
      competitions: ['HOSA competitive events', 'Science Olympiad (anatomy)', 'Red Cross youth programs'] },
    { id: 'physician-assistant', title: 'Physician Assistant', emoji: '🧑‍⚕️', cat: 'health', pay: 135880, growth: 21, edu: "Master's degree", usn: 5,
      summary: 'Works on a medical team to examine patients, diagnose problems, and prescribe treatment, in just about any specialty.',
      does: ['Take medical histories and examine patients', 'Order and read tests, then diagnose', 'Assist in surgery or create treatment plans with doctors'],
      traits: { I: 3, S: 2, R: 1 }, subjects: ['Biology', 'Chemistry', 'Math'],
      keywords: ['medicine', 'health', 'doctor', 'biology', 'science', 'helping', 'hospital', 'anatomy', 'body'],
      skills: ['Biology & chemistry', 'Problem solving', 'Teamwork', 'Clear communication'], domains: ['science', 'people', 'stats'],
      path: path(['Strong math and science classes', 'Learn about the human body', 'Try first aid training'], ['Honors Biology', 'Join HOSA', 'Volunteer in a healthcare setting'], ['Honors Chemistry', 'CPR certification', 'Shadow a PA or doctor'], ['AP Biology', 'AP Statistics', 'Hospital or clinic volunteering'], ['Apply to biology or health science programs', 'Start collecting patient-care hours (volunteer or EMT)']),
      competitions: ['HOSA competitive events', 'USA Biology Olympiad (USABO)', 'Science fair (ISEF)'] },
    { id: 'speech-pathologist', title: 'Speech-Language Pathologist', emoji: '🗣️', cat: 'health', pay: 97870, growth: 17, edu: "Master's degree", usn: 9,
      summary: 'Helps people of all ages speak, understand, swallow, and communicate better, from kids learning sounds to adults recovering from a stroke.',
      does: ['Test how well someone speaks, understands, or swallows', 'Plan fun exercises and therapy for each person', 'Work with teachers, doctors, and families'],
      traits: { S: 3, I: 2, A: 1 }, subjects: ['English', 'Psychology', 'Biology'],
      keywords: ['speech', 'language', 'helping', 'kids', 'teaching', 'communication', 'words', 'talking', 'languages'],
      skills: ['Patience & empathy', 'Language & sounds', 'Creativity', 'Observation'], domains: ['people', 'writing', 'science'],
      path: path(['Notice how language and sounds work', 'Help younger kids read', 'Study a foreign language'], ['Honors English', 'Peer tutoring', 'Foreign language'], ['Psychology', 'Volunteer with kids or seniors', 'Sign language club'], ['AP Psychology', 'AP Biology', 'Shadow a speech therapist at a school'], ['Apply to communication sciences & disorders programs', 'Volunteer in a therapy clinic']),
      competitions: ['HOSA behavioral health events', 'Speech & debate', 'Science fair (language or behavior)'] },
    { id: 'occupational-therapist', title: 'Occupational Therapist', emoji: '🖐️', cat: 'health', pay: 100330, growth: 15, edu: "Master's degree", usn: 20,
      summary: 'Helps people recover and do everyday things (writing, cooking, working, playing) after an injury, illness, or disability.',
      does: ['Evaluate what daily tasks are hard for a person', 'Design activities and tools that help them improve', 'Teach families how to support progress at home'],
      traits: { S: 3, R: 2, I: 1 }, subjects: ['Biology', 'Psychology', 'Art'],
      keywords: ['helping', 'therapy', 'kids', 'crafts', 'health', 'creative', 'body', 'sports', 'people'],
      skills: ['Empathy', 'Creative problem solving', 'Anatomy basics', 'Patience'], domains: ['people', 'science', 'design'],
      path: path(['Try hands-on crafts and building', 'Volunteer with younger kids', 'Learn about the body'], ['Biology', 'Join HOSA', 'Volunteer at a senior center'], ['Psychology', 'Art or design class', 'Shadow an occupational therapist'], ['AP Biology or Anatomy', 'AP Psychology', 'Volunteer in a therapy clinic'], ['Apply to health science or psychology programs', 'Collect observation hours']),
      competitions: ['HOSA events', 'Science fair (behavioral science)', 'Invention conventions'] },
    { id: 'physical-therapist', title: 'Physical Therapist', emoji: '🏃', cat: 'health', pay: 102760, growth: 12, edu: 'Doctoral degree', usn: 37,
      summary: 'Helps people move better and feel less pain after injuries, surgeries, and illnesses, including athletes getting back in the game.',
      does: ['Evaluate how a person moves and where it hurts', 'Create exercise and treatment plans', 'Coach patients through recovery step by step'],
      traits: { S: 2, R: 2, I: 2 }, subjects: ['Biology', 'Physics', 'PE / Health'],
      keywords: ['sports', 'soccer', 'basketball', 'fitness', 'health', 'body', 'helping', 'athletes', 'exercise', 'injury'],
      skills: ['Anatomy', 'Physics of movement', 'Motivation & coaching', 'Observation'], domains: ['science', 'people', 'stats'],
      path: path(['Play a sport or train regularly', 'Learn how muscles and bones work', 'Help coach younger players'], ['Biology', 'PE / health electives', 'Join HOSA'], ['Chemistry', 'Anatomy & physiology if offered', 'Shadow a physical therapist'], ['AP Biology', 'AP Physics 1', 'Volunteer in a clinic'], ['Apply to kinesiology or health science programs', 'Collect observation hours in different settings']),
      competitions: ['HOSA events', 'Science Olympiad (anatomy)', 'Science fair (sports science)'] },
    { id: 'veterinarian', title: 'Veterinarian', emoji: '🐶', cat: 'health', pay: 130100, growth: 9, edu: 'Doctoral degree (DVM)',
      summary: 'A doctor for animals: treat pets, farm animals, or wildlife, and help keep animals and people healthy.',
      does: ['Examine animals and diagnose illness or injury', 'Perform surgery and vaccinations', 'Talk with owners about care and treatment'],
      traits: { I: 3, S: 2, R: 2 }, subjects: ['Biology', 'Chemistry', 'Math'],
      keywords: ['animals', 'dog', 'cat', 'pets', 'horses', 'zoo', 'wildlife', 'biology', 'nature', 'farm'],
      skills: ['Biology & chemistry', 'Compassion', 'Calm hands', 'Communication with owners'], domains: ['science', 'people', 'stats'],
      path: path(['Care for a pet or volunteer at an animal shelter', 'Join 4-H or nature clubs', 'Strong science classes'], ['Honors Biology', 'Volunteer at a shelter or vet clinic', 'Join FFA or 4-H if available'], ['Honors Chemistry', 'Shadow a veterinarian', 'Animal-care work experience'], ['AP Biology', 'AP Statistics', 'Keep logging animal-experience hours'], ['Apply to animal science or biology programs', 'Seek vet-clinic or wildlife internships']),
      competitions: ['FFA events', '4-H competitions', 'Science fair (animal science)'] },
    { id: 'dentist', title: 'Dentist', emoji: '🦷', cat: 'health', pay: 176110, growth: 6, edu: 'Doctoral degree (DDS or DMD)',
      summary: 'Keeps teeth and mouths healthy: fill cavities, fix smiles, and help people prevent problems. Often runs their own practice.',
      does: ['Examine teeth and take X-rays', 'Fill cavities, repair teeth, and perform small surgeries', 'Teach patients how to care for their teeth'],
      traits: { R: 3, I: 2, S: 1 }, subjects: ['Biology', 'Chemistry', 'Art'],
      keywords: ['teeth', 'dentist', 'health', 'detail', 'hands', 'biology', 'science', 'sculpting', 'art', 'smile'],
      skills: ['Steady hands', 'Biology & chemistry', 'Attention to detail', 'Putting people at ease'], domains: ['science', 'design', 'people'],
      path: path(['Strong science classes', 'Try sculpting, drawing, or model building for fine motor skills', 'Take care of your own teeth!'], ['Honors Biology', 'Art or design class', 'Join HOSA'], ['Honors Chemistry', 'Shadow a dentist', 'Hands-on hobbies like model building'], ['AP Biology', 'AP Chemistry', 'Dental-office volunteering'], ['Apply to biology or pre-dental programs', 'Prepare for the Dental Admission Test later in college']),
      competitions: ['HOSA events', 'Science fair', 'Art or sculpture contests'] },
    { id: 'athletic-trainer', title: 'Athletic Trainer', emoji: '🏅', cat: 'health', pay: 62520, growth: 13, edu: "Master's degree",
      summary: 'Keeps athletes healthy: prevent injuries, give first-response care on the sideline, and guide recovery.',
      does: ['Tape, brace, and treat injuries', 'Create injury-prevention and recovery plans', 'Be on the sideline during games and practices'],
      traits: { S: 2, R: 2, I: 1 }, subjects: ['Biology', 'PE / Health', 'Psychology'],
      keywords: ['sports', 'soccer', 'football', 'basketball', 'fitness', 'athlete', 'team', 'coach', 'health', 'injury'],
      skills: ['Anatomy', 'First aid', 'Communication', 'Staying calm in fast moments'], domains: ['science', 'people', 'stats'],
      path: path(['Play sports and notice how injuries happen', 'Learn first aid', 'Be a team manager or helper'], ['Biology', 'PE / health', 'Student athletic trainer or team manager'], ['Anatomy & physiology if offered', 'CPR/first aid certification', 'Assist your school\'s athletic trainer'], ['AP Biology', 'AP Psychology', 'Shadow an athletic trainer'], ['Apply to athletic training or kinesiology programs', 'Work at a sports camp or clinic']),
      competitions: ['HOSA sports medicine events', 'Science fair (sports science)', 'Red Cross first-aid programs'] },
    { id: 'health-services-manager', title: 'Health Services Manager', emoji: '🏥', cat: 'health', pay: 123860, growth: 24, edu: "Bachelor's degree", usn: 6,
      summary: 'Runs the business side of healthcare: hospitals, clinics, and care teams, so doctors and nurses can focus on patients.',
      does: ['Plan budgets, schedules, and staffing for a clinic or hospital', 'Make sure care is safe and follows the rules', 'Lead teams and solve problems fast'],
      traits: { E: 3, S: 2, C: 2 }, subjects: ['Economics', 'Biology', 'English'],
      keywords: ['leader', 'organizing', 'business', 'health', 'helping', 'management', 'planning', 'hospital', 'team'],
      skills: ['Leadership', 'Budgeting', 'Healthcare basics', 'Communication'], domains: ['people', 'economics', 'stats'],
      path: path(['Lead a club or team project', 'Learn how money and budgets work', 'Volunteer in healthcare'], ['Economics or personal finance', 'Join DECA or FBLA', 'Student government'], ['Biology', 'Business class', 'Volunteer at a hospital or clinic'], ['AP Economics', 'AP Statistics', 'Lead a service project'], ['Apply to health administration, business, or public health programs', 'Intern at a local clinic or hospital']),
      competitions: ['DECA (Health Services Marketing)', 'FBLA', 'HOSA events'] },
    { id: 'it-manager', title: 'IT Manager', emoji: '🖥️', cat: 'tech', pay: 175140, growth: 16, edu: "Bachelor's degree", usn: 3,
      summary: 'Leads the people and technology that keep a company running: networks, apps, data, and security.',
      does: ['Decide which technology a company should use', 'Lead teams of programmers and tech support', 'Plan budgets and keep systems secure and running'],
      traits: { E: 2, I: 2, C: 2 }, subjects: ['Computer Science', 'Economics', 'Math'],
      keywords: ['computers', 'tech', 'leader', 'coding', 'team', 'organizing', 'business', 'it', 'networks'],
      skills: ['Programming basics', 'Leadership', 'Project planning', 'Explaining tech simply'], domains: ['coding', 'people', 'economics'],
      path: path(['Learn Scratch, then Python', 'Take apart (or build) a computer', 'Lead a group project'], ['Intro to Computer Science', 'Join a coding or robotics club', 'Student tech support team'], ['AP Computer Science Principles', 'Business or economics class', 'Run a school tech project'], ['AP Computer Science A', 'AP Economics', 'Lead a club or hackathon team'], ['Apply to computer science, information systems, or business programs', 'Internship in an IT department']),
      competitions: ['Congressional App Challenge', 'FBLA (Computer Problem Solving)', 'Hackathons'] },
    { id: 'cybersecurity', title: 'Cybersecurity Analyst', emoji: '🛡️', cat: 'tech', pay: 129180, growth: 21, edu: "Bachelor's degree", usn: 4,
      summary: 'A digital detective and guard: find weak spots in computer systems and stop hackers before they do damage.',
      does: ['Monitor networks for attacks', 'Test systems to find weaknesses (ethical hacking)', 'Respond fast when something goes wrong'],
      traits: { I: 3, C: 2, R: 1 }, subjects: ['Computer Science', 'Math'],
      keywords: ['hacking', 'security', 'computers', 'puzzles', 'coding', 'games', 'cyber', 'logic', 'ctf', 'detective'],
      skills: ['Programming (Python)', 'Logical thinking', 'Networking basics', 'Curiosity about how things break'], domains: ['coding', 'logic', 'math'],
      path: path(['Learn Python', 'Try beginner puzzle and cipher challenges', 'Learn how the internet works'], ['Intro to Computer Science', 'Join a cyber club', 'Play beginner CTF games (picoCTF)'], ['AP Computer Science Principles', 'Learn Linux basics', 'CyberPatriot team'], ['AP Computer Science A', 'Discrete math or AP Calculus', 'Compete in CTFs'], ['Apply to cybersecurity or computer science programs', 'Earn an entry-level certificate (like CompTIA Security+)']),
      competitions: ['CyberPatriot', 'picoCTF', 'National Cyber Scholarship Foundation'] },
    { id: 'web-developer', title: 'Web & App Designer-Developer', emoji: '🌐', cat: 'tech', pay: 99520, growth: 5, edu: "Bachelor's degree or equivalent skills",
      summary: 'Design and build the websites and apps you use every day: part artist, part engineer.',
      does: ['Turn designs into working websites and apps', 'Make sites fast and easy on phones and computers', 'Test with real users and keep improving'],
      traits: { I: 2, A: 2, R: 1 }, subjects: ['Computer Science', 'Art', 'English'],
      keywords: ['website', 'web', 'coding', 'apps', 'design', 'creative', 'computers', 'minecraft', 'youtube'],
      skills: ['HTML/CSS/JavaScript', 'Design sense', 'Problem solving', 'Attention to detail'], domains: ['coding', 'design', 'writing'],
      path: path(['Make a simple website', 'Learn HTML and CSS', 'Start a digital portfolio'], ['Intro to Computer Science', 'Digital art or graphic design', 'Build a site for a club'], ['AP Computer Science Principles', 'Learn JavaScript', 'Design a real site for a local group'], ['AP Computer Science A', 'Take on freelance or volunteer web projects', 'Learn about design for real users'], ['Build a portfolio site and GitHub profile', 'Apply to computer science, design, or HCI programs']),
      competitions: ['Congressional App Challenge', 'FBLA Website Design', 'Hackathons'] },
    { id: 'game-developer', title: 'Video Game Developer', emoji: '🎮', cat: 'tech', pay: 134040, growth: 10, edu: "Bachelor's degree (software developer data)",
      summary: 'Build the games millions of people play: code the rules, design the levels, and polish the fun.',
      does: ['Program game rules, characters, and physics', 'Design levels and test whether they are fun', 'Work with artists, writers, and sound designers'],
      traits: { I: 2, A: 2, R: 2 }, subjects: ['Computer Science', 'Art', 'Math'],
      keywords: ['gaming', 'games', 'video games', 'minecraft', 'roblox', 'fortnite', 'coding', 'design', 'story', 'animation'],
      skills: ['Programming', 'Game design', 'Math & physics', 'Creativity and teamwork'], domains: ['coding', 'design', 'logic'],
      path: path(['Make a game in Scratch or Roblox Studio', 'Play games and ask why they are fun', 'Learn basic Python'], ['Intro to Computer Science', 'Try Unity or Godot (free)', 'Join a game-dev club'], ['AP Computer Science Principles', 'Finish a small game and publish it', 'Take art or music class'], ['AP Computer Science A', 'AP Physics 1', 'Join a game jam'], ['Build a game portfolio', 'Apply to computer science or game design programs']),
      competitions: ['Game jams (itch.io, Global Game Jam)', 'Congressional App Challenge', 'National STEM video game challenge'] },
    { id: 'financial-manager', title: 'Financial Manager', emoji: '🏦', cat: 'business', pay: 166570, growth: 10, edu: "Bachelor's degree", usn: 2,
      summary: 'Guides an organization\'s money decisions: budgets, investments, and long-term plans. Ranked the #2 best job overall.',
      does: ['Create financial reports and forecasts', 'Decide how to invest and spend money wisely', 'Lead a team of accountants and analysts'],
      traits: { C: 3, E: 2, I: 1 }, subjects: ['Math', 'Economics', 'Computer Science'],
      keywords: ['money', 'numbers', 'business', 'budget', 'stocks', 'saving', 'math', 'spreadsheets', 'leader'],
      skills: ['Math & statistics', 'Spreadsheets', 'Leadership', 'Clear reporting'], domains: ['economics', 'math', 'stats'],
      path: path(['Track your own money (allowance, savings)', 'Get ahead in math', 'Try a stock market simulation'], ['Personal finance class', 'Join FBLA', 'Learn spreadsheets'], ['Algebra 2 / Pre-calculus', 'Economics', 'Run a budget for a club'], ['AP Economics', 'AP Statistics', 'Treasurer of a club'], ['Apply to finance, accounting, or business programs', 'Internship at a bank or local business']),
      competitions: ['National Economics Challenge', 'FBLA events', 'Stock Market Game'] },
    { id: 'marketing-manager', title: 'Marketing Manager', emoji: '📣', cat: 'business', pay: 165780, growth: 6, edu: "Bachelor's degree",
      summary: 'Figure out what people want, then tell the story that makes them care: brands, campaigns, and social media.',
      does: ['Study what customers want', 'Plan ads, videos, and social campaigns', 'Track the numbers to see what worked'],
      traits: { E: 3, A: 2, S: 1 }, subjects: ['English', 'Economics', 'Art'],
      keywords: ['social media', 'youtube', 'tiktok', 'ads', 'brands', 'business', 'creative', 'selling', 'influencer', 'videos', 'writing'],
      skills: ['Storytelling', 'Persuasion', 'Data basics', 'Creativity'], domains: ['people', 'writing', 'economics'],
      path: path(['Promote a club, event, or small business', 'Study ads you like and ask why they work', 'Practice speaking and writing'], ['Business or marketing class', 'Join DECA', 'Run your school\'s social account'], ['Graphic design basics', 'Create a real campaign for an event', 'Learn basic analytics'], ['AP Economics', 'AP English Language', 'Lead a marketing team in DECA'], ['Apply to business, marketing, or communications programs', 'Intern with a local business']),
      competitions: ['DECA marketing events', 'FBLA events', 'Junior Achievement'] },
    { id: 'actuary', title: 'Actuary', emoji: '📉', cat: 'business', pay: 130000, growth: 9, edu: "Bachelor's degree",
      summary: 'A math detective of risk: use statistics to predict what might go wrong (like accidents or illness) and put a price on it.',
      does: ['Use data to estimate how likely events are', 'Help insurance companies set fair prices', 'Pass professional exams and explain results'],
      traits: { C: 3, I: 3 }, subjects: ['Math', 'Economics', 'Computer Science'],
      keywords: ['math', 'statistics', 'numbers', 'probability', 'puzzles', 'data', 'risk', 'insurance', 'chess', 'games'],
      skills: ['Probability & statistics', 'Spreadsheets & coding', 'Persistence for exams', 'Clear explanations'], domains: ['math', 'stats', 'economics'],
      path: path(['Math contests (MATHCOUNTS, AMC 8)', 'Learn probability with card and dice games', 'Get ahead in math'], ['Geometry / Algebra 2', 'AMC 10', 'Personal finance'], ['Pre-calculus', 'Intro to coding (Python)', 'Study how insurance works'], ['AP Statistics', 'AP Calculus', 'Economics'], ['Apply to math, statistics, or actuarial science programs', 'Take the first actuarial exam (P) in college']),
      competitions: ['MATHCOUNTS', 'AMC 8/10/12', 'Actuarial science competitions in college'] },
    { id: 'electrician', title: 'Electrician', emoji: '⚡', cat: 'build', pay: 63190, growth: 9, edu: 'High school diploma + paid apprenticeship',
      summary: 'Install and repair the wiring that powers homes, hospitals, and solar farms. You earn while you learn, with no college debt required.',
      does: ['Read blueprints and install wiring', 'Find and fix electrical problems', 'Follow safety codes to keep people safe'],
      traits: { R: 3, C: 1, I: 1 }, subjects: ['Math', 'Physics', 'Computer Science'],
      keywords: ['building', 'fixing', 'tools', 'electronics', 'circuits', 'hands-on', 'solar', 'lego', 'robots', 'trade'],
      skills: ['Math (algebra)', 'Electrical basics', 'Safety habits', 'Problem solving'], domains: ['math', 'science', 'logic'],
      path: path(['Build circuits with kits', 'Take apart safe old electronics (with an adult)', 'Strong math classes'], ['Algebra', 'Shop or electronics class', 'Join SkillsUSA if available'], ['Physics', 'Career & technical education (CTE) electrical class', 'Shadow an electrician'], ['Advanced CTE or dual-enrollment trade courses', 'Safety certification (like OSHA 10)'], ['Apply for an electrician apprenticeship (4–5 years, paid)', 'Or enroll in a trade school program']),
      competitions: ['SkillsUSA Electrical Construction Wiring', 'Local trade skill contests', 'Science Olympiad (circuits)'] },
    { id: 'civil-engineer', title: 'Civil Engineer', emoji: '🌉', cat: 'build', pay: 100840, growth: 6, edu: "Bachelor's degree",
      summary: 'Design and build what everybody uses: bridges, roads, dams, airports, and clean water systems.',
      does: ['Design bridges, roads, and water systems', 'Visit construction sites and check the work', 'Use math and software to keep structures safe'],
      traits: { R: 2, I: 3, C: 1 }, subjects: ['Math', 'Physics', 'Computer Science'],
      keywords: ['building', 'bridges', 'minecraft', 'lego', 'cities', 'design', 'construction', 'math', 'engineering', 'roads'],
      skills: ['Math through calculus', 'Physics of structures', '3D design software', 'Teamwork'], domains: ['math', 'science', 'design'],
      path: path(['Build bridges and towers from paper, sticks, or LEGO', 'Try Minecraft redstone or city builders', 'Get ahead in math'], ['Geometry', 'Intro to engineering design', 'Join Science Olympiad (bridge building)'], ['Pre-calculus', 'Learn CAD (Tinkercad, Fusion 360)', 'Visit a construction site (with a program)'], ['AP Physics 1', 'AP Calculus', 'Lead a build team'], ['Apply to civil engineering programs', 'Summer engineering program or internship']),
      competitions: ['Science Olympiad (Towers, Bridges)', 'FIRST Robotics', 'TEAMS engineering competition'] },
    { id: 'pilot', title: 'Pilot', emoji: '✈️', cat: 'build', pay: 210020, growth: 7, edu: "Bachelor's degree for airlines + flight training", usn: 10,
      summary: 'Fly passengers, cargo, or rescue missions. A mix of science, split-second decisions, and travel.',
      does: ['Plan routes and check weather and the aircraft', 'Fly the plane and talk with air traffic control', 'Lead the crew and keep everyone safe'],
      traits: { R: 2, I: 2, C: 2 }, subjects: ['Math', 'Physics', 'Computer Science'],
      keywords: ['planes', 'flying', 'aviation', 'travel', 'space', 'drones', 'adventure', 'airplane', 'airport'],
      skills: ['Math & physics', 'Staying calm', 'Checklists & precision', 'Teamwork'], domains: ['math', 'science', 'logic'],
      path: path(['Learn how planes fly (paper airplanes count!)', 'Try a flight simulator', 'Join a model aircraft or Civil Air Patrol cadet group'], ['Algebra 2', 'Physics', 'Civil Air Patrol or Young Eagles flight'], ['Pre-calculus', 'Aviation or drone class if offered', 'Intro flight lesson'], ['AP Physics 1', 'AP Calculus', 'Start private pilot ground school'], ['Apply to aviation, engineering, or flight-training programs', 'Medical certificate check-up with an aviation doctor']),
      competitions: ['Civil Air Patrol', 'Science Olympiad (Flight)', 'Drone competitions'] },
    { id: 'video-producer', title: 'Video Producer & Editor', emoji: '🎬', cat: 'creative', pay: 75100, growth: 3, edu: "Bachelor's degree (film editors & camera operators)",
      summary: 'Tell stories with video: films, YouTube channels, news, ads, and shows. Create, shoot, edit, and publish.',
      does: ['Plan and shoot video', 'Edit footage, music, and effects into a story', 'Work with writers, actors, and clients'],
      traits: { A: 3, E: 1, R: 1 }, subjects: ['Art', 'English', 'Computer Science'],
      keywords: ['youtube', 'videos', 'filming', 'editing', 'tiktok', 'movies', 'stories', 'animation', 'creative', 'photography', 'content'],
      skills: ['Storytelling', 'Video editing software', 'Visual eye', 'Patience & deadlines'], domains: ['design', 'writing', 'people'],
      path: path(['Make short videos with a phone', 'Study how your favorite videos are edited', 'Write a simple script'], ['Media or film class', 'Join the school news or video club', 'Learn free editing software'], ['Photography', 'Make a short film or documentary', 'Build a YouTube or portfolio channel'], ['AP Art & Design or media', 'AP English', 'Shoot for school events'], ['Build a demo reel', 'Apply to film, media, or communications programs']),
      competitions: ['Student film festivals', 'C-SPAN StudentCam', 'Scholastic Art & Writing Awards (film)'] },
  ];

  EXTRA.forEach((c) => { if (!c.tasks) c.tasks = []; D.CAREERS.push(c); });

  // Tap-to-pick interests for the quick start. `kw` words feed career matching.
  D.INTEREST_TILES = [
    { id: 'gaming', emoji: '🎮', label: 'Video games', kw: ['gaming', 'games', 'video games'] },
    { id: 'coding', emoji: '💻', label: 'Coding & computers', kw: ['coding', 'computers', 'computer', 'apps', 'website'] },
    { id: 'art', emoji: '🎨', label: 'Drawing & art', kw: ['art', 'drawing', 'design', 'creative'] },
    { id: 'videos', emoji: '🎬', label: 'Making videos', kw: ['youtube', 'videos', 'filming', 'editing', 'content'] },
    { id: 'music', emoji: '🎵', label: 'Music', kw: ['music', 'creative'] },
    { id: 'writing', emoji: '✍️', label: 'Writing & stories', kw: ['writing', 'reading', 'stories', 'books'] },
    { id: 'sports', emoji: '⚽', label: 'Sports & fitness', kw: ['sports', 'soccer', 'basketball', 'fitness', 'athlete', 'team'] },
    { id: 'animals', emoji: '🐾', label: 'Animals', kw: ['animals', 'pets', 'dog', 'cat', 'biology'] },
    { id: 'nature', emoji: '🌱', label: 'Nature & climate', kw: ['nature', 'outdoors', 'climate', 'plants', 'environment'] },
    { id: 'science', emoji: '🔬', label: 'Science experiments', kw: ['science', 'experiments', 'biology', 'chemistry', 'space'] },
    { id: 'space', emoji: '🚀', label: 'Space & flying', kw: ['space', 'planes', 'flying', 'aviation', 'rockets'] },
    { id: 'building', emoji: '🔧', label: 'Building & fixing', kw: ['building', 'fixing', 'tools', 'lego', 'minecraft', 'robots', 'hands-on'] },
    { id: 'puzzles', emoji: '🧩', label: 'Puzzles & strategy', kw: ['puzzles', 'chess', 'logic', 'math', 'games'] },
    { id: 'business', emoji: '💼', label: 'Business & money', kw: ['business', 'money', 'selling', 'stocks', 'saving', 'leader'] },
    { id: 'helping', emoji: '🤝', label: 'Helping people', kw: ['helping', 'caring', 'people', 'health', 'kids', 'teaching'] },
    { id: 'speaking', emoji: '🎤', label: 'Debating & speaking', kw: ['debate', 'speech', 'arguing', 'politics', 'justice', 'fairness'] },
  ];

  D.growthText = (g) => (g == null ? '' : g >= 10 ? 'Growing fast' : g >= 5 ? 'Growing' : g >= 1 ? 'Steady' : g === 0 ? 'No change' : 'Shrinking');
})();
