// Pathfinder content: personality test, careers, roadmaps, and practice banks.
window.PF_DATA = (function () {
  const TRAITS = {
    R: { name: 'Builder', desc: 'Hands-on, practical, likes making and fixing things.' },
    I: { name: 'Thinker', desc: 'Curious, analytical, loves solving puzzles and asking why.' },
    A: { name: 'Creator', desc: 'Imaginative, expressive, enjoys art, stories, and design.' },
    S: { name: 'Helper', desc: 'Caring, patient, energized by helping and teaching others.' },
    E: { name: 'Leader', desc: 'Confident, persuasive, likes leading teams and big ideas.' },
    C: { name: 'Organizer', desc: 'Careful, detail-oriented, likes plans, lists, and systems.' },
  };

  // Likert statements (1 = Not me, 5 = Totally me), three per trait.
  const QUESTIONS = [
    { t: 'R', q: 'I like building things — LEGO, models, robots, or crafts.' },
    { t: 'I', q: 'I enjoy solving puzzles, riddles, or tricky math problems.' },
    { t: 'A', q: 'I often draw, write stories, make music, or design things for fun.' },
    { t: 'S', q: 'Friends come to me when they need advice or help.' },
    { t: 'E', q: 'I like being the one who leads a group project.' },
    { t: 'C', q: 'I keep my notes, room, or files neat and organized.' },
    { t: 'I', q: 'I wonder how things work and look up answers on my own.' },
    { t: 'R', q: 'I would rather do a hands-on experiment than read about it.' },
    { t: 'S', q: 'I enjoy explaining things to younger kids or classmates.' },
    { t: 'A', q: 'I like coming up with original ideas nobody has tried before.' },
    { t: 'C', q: 'I like following a clear plan and checking things off a list.' },
    { t: 'E', q: 'I enjoy convincing people, debating, or selling an idea.' },
    { t: 'I', q: 'Science and math class are usually where I feel most interested.' },
    { t: 'R', q: 'I like being outdoors, working with tools, or playing sports.' },
    { t: 'A', q: 'I notice colors, layouts, and style in things around me.' },
    { t: 'S', q: 'I care a lot about making the world fairer or healthier for people.' },
    { t: 'E', q: 'I dream about starting my own business or club someday.' },
    { t: 'C', q: 'I am good with numbers, budgets, or keeping track of details.' },
  ];

  const SUBJECTS = ['Math', 'Biology', 'Chemistry', 'Physics', 'Computer Science', 'English',
    'History', 'Government', 'Economics', 'Art', 'Music', 'Psychology', 'Foreign Language', 'PE / Health'];

  const STAGES = [
    { key: 'ms', label: 'Middle School (6–8)' },
    { key: '9', label: 'Grade 9' },
    { key: '10', label: 'Grade 10' },
    { key: '11', label: 'Grade 11' },
    { key: '12', label: 'Grade 12' },
  ];

  const CAREERS = [
    {
      id: 'data-scientist', title: 'Data Scientist', emoji: '📊',
      summary: 'Finds patterns in data to answer questions and build smart (AI) systems.',
      traits: { I: 3, C: 2, R: 1 }, subjects: ['Math', 'Computer Science', 'Economics'],
      keywords: ['data', 'numbers', 'math', 'coding', 'computer', 'puzzle', 'statistics', 'ai', 'sports stats', 'chess', 'games'],
      skills: ['Statistics & probability', 'Python programming', 'Algebra → Calculus', 'Explaining results clearly'],
      domains: ['math', 'stats', 'coding'],
      path: {
        ms: ['Get ahead in math: aim for Pre-Algebra/Algebra 1 by 8th grade', 'Try block coding, then intro Python (Scratch → Python)', 'Join MATHCOUNTS or a school math club'],
        9: ['Geometry or Algebra 2 (honors if possible)', 'Intro to Computer Science', 'Take the AMC 10 in fall'],
        10: ['Algebra 2 / Pre-Calculus', 'AP Computer Science Principles', 'Start a small data project (sports, weather, music stats)'],
        11: ['AP Statistics', 'AP Calculus AB/BC', 'AP Computer Science A', 'Enter a Kaggle beginner competition or science fair with data'],
        12: ['Multivariable calc or dual-enrollment college math', 'Build a portfolio on GitHub', 'Apply to Statistics / Data Science / CS programs'],
      },
      competitions: ['MATHCOUNTS (MS)', 'AMC 8 (MS)', 'AMC 10/12 → AIME', 'USA Computing Olympiad (USACO)', 'Kaggle Learn & beginner competitions', 'Regeneron / ISEF science fair'],
      tasks: [
        { title: 'Statistics lesson: mean, median, and spread', skill: 'Statistics' },
        { title: 'Python practice: loops and lists', skill: 'Coding' },
        { title: 'Competition math problem set (AMC-style)', skill: 'Math' },
        { title: 'Explore a dataset and write down 3 findings', skill: 'Data analysis' },
        { title: 'Read about a real AI / machine learning application', skill: 'Big picture' },
        { title: 'Make a chart from data you collected yourself', skill: 'Visualization' },
      ],
    },
    {
      id: 'software-engineer', title: 'Software Engineer', emoji: '💻',
      summary: 'Designs and builds apps, games, and websites that millions of people use.',
      traits: { I: 3, R: 2, C: 1 }, subjects: ['Computer Science', 'Math', 'Physics'],
      keywords: ['coding', 'computer', 'games', 'video games', 'apps', 'website', 'robot', 'tech', 'minecraft', 'build'],
      skills: ['Programming (Python, Java, JavaScript)', 'Logical problem solving', 'Algorithms & data structures', 'Teamwork'],
      domains: ['coding', 'logic', 'math'],
      path: {
        ms: ['Learn Scratch, then Python or JavaScript', 'Join a robotics club (FIRST LEGO League)', 'Build a simple game or website'],
        9: ['Intro to Computer Science', 'Geometry / Algebra 2', 'Try USACO Bronze'],
        10: ['AP Computer Science Principles', 'Join or start a coding club / hackathon team', 'Publish a project on GitHub'],
        11: ['AP Computer Science A', 'AP Calculus', 'Compete in hackathons or Congressional App Challenge'],
        12: ['Data structures (dual enrollment or online course)', 'Internship or open-source contributions', 'Apply to CS / Software Engineering programs'],
      },
      competitions: ['FIRST LEGO League (MS)', 'FIRST Robotics (HS)', 'USA Computing Olympiad (USACO)', 'Congressional App Challenge', 'American Computer Science League', 'Local hackathons'],
      tasks: [
        { title: 'Code a small program: number guessing game', skill: 'Coding' },
        { title: 'Solve 2 beginner algorithm problems', skill: 'Algorithms' },
        { title: 'Learn one new programming concept (functions, arrays…)', skill: 'Coding' },
        { title: 'Work on your personal project for one session', skill: 'Building' },
        { title: 'Read and understand someone else\'s code', skill: 'Code reading' },
        { title: 'Logic puzzle practice', skill: 'Logic' },
      ],
    },
    {
      id: 'physician', title: 'Doctor (Physician)', emoji: '🩺',
      summary: 'Diagnoses and treats illness, helping patients live healthier lives.',
      traits: { I: 3, S: 3, R: 1 }, subjects: ['Biology', 'Chemistry', 'Math', 'Psychology'],
      keywords: ['medicine', 'doctor', 'health', 'helping', 'biology', 'body', 'hospital', 'animals', 'science', 'care'],
      skills: ['Biology & chemistry', 'Communication & empathy', 'Memory & study habits', 'Data / statistics literacy'],
      domains: ['science', 'people', 'math'],
      path: {
        ms: ['Take advanced science and math', 'Join science club or Science Olympiad', 'Learn first aid / CPR basics'],
        9: ['Honors Biology', 'Algebra 2 / Geometry', 'Volunteer at a community health event'],
        10: ['Honors Chemistry', 'Join HOSA (Future Health Professionals)', 'Shadow a doctor or nurse if possible'],
        11: ['AP Biology', 'AP Chemistry', 'AP Statistics or Psychology', 'Hospital volunteering'],
        12: ['AP Physics or Anatomy & Physiology', 'Research or summer medical program', 'Apply to pre-med friendly colleges (Biology, Biochem)'],
      },
      competitions: ['Science Olympiad (MS & HS)', 'HOSA competitive events', 'USA Biology Olympiad (USABO)', 'Brain Bee neuroscience competition', 'Science fair (ISEF)'],
      tasks: [
        { title: 'Study a body system (heart, lungs, brain…)', skill: 'Biology' },
        { title: 'Chemistry concept review: atoms and bonds', skill: 'Chemistry' },
        { title: 'Make flashcards for 10 science terms', skill: 'Memory' },
        { title: 'Read a health news article and summarize it', skill: 'Communication' },
        { title: 'Practice biology olympiad-style questions', skill: 'Biology' },
        { title: 'Learn about a disease and how it is treated', skill: 'Medicine' },
      ],
    },
    {
      id: 'mech-engineer', title: 'Mechanical Engineer', emoji: '⚙️',
      summary: 'Designs machines — from cars and rockets to prosthetic hands.',
      traits: { R: 3, I: 3, C: 1 }, subjects: ['Physics', 'Math', 'Computer Science'],
      keywords: ['build', 'robot', 'cars', 'machines', 'lego', 'rockets', 'fix', 'engines', 'drones', 'tools', 'space'],
      skills: ['Physics & mechanics', 'Math through calculus', 'CAD / 3D design', 'Hands-on building'],
      domains: ['math', 'science', 'logic'],
      path: {
        ms: ['Robotics club (FIRST LEGO League / VEX IQ)', 'Get ahead in math', 'Build kits: rockets, circuits, models'],
        9: ['Geometry / Algebra 2', 'Intro to Engineering Design (if offered)', 'Join FIRST Robotics or VEX'],
        10: ['Pre-Calculus', 'Chemistry', 'Learn a CAD tool (Tinkercad → Fusion 360)'],
        11: ['AP Physics 1 / C', 'AP Calculus', 'Lead a build on your robotics team'],
        12: ['AP Physics C', 'Engineering summer program or internship', 'Apply to Mechanical / Aerospace Engineering'],
      },
      competitions: ['FIRST LEGO League (MS)', 'VEX Robotics', 'FIRST Robotics Competition', 'Science Olympiad build events', 'Physics Bowl / F=ma exam', 'TEAMS engineering competition'],
      tasks: [
        { title: 'Physics lesson: forces and motion', skill: 'Physics' },
        { title: 'Design something in a 3D/CAD tool', skill: 'CAD' },
        { title: 'Algebra / geometry problem set', skill: 'Math' },
        { title: 'Take apart (or research) how a machine works', skill: 'Mechanics' },
        { title: 'Sketch an invention and label its parts', skill: 'Design' },
        { title: 'Work on a build project for one session', skill: 'Building' },
      ],
    },
    {
      id: 'graphic-designer', title: 'Graphic / UX Designer', emoji: '🎨',
      summary: 'Creates logos, apps, posters, and experiences that look great and are easy to use.',
      traits: { A: 3, E: 1, R: 1 }, subjects: ['Art', 'Computer Science', 'English'],
      keywords: ['art', 'drawing', 'design', 'painting', 'colors', 'photography', 'fashion', 'animation', 'apps', 'creative'],
      skills: ['Drawing & visual composition', 'Design tools', 'Typography & color', 'Understanding users'],
      domains: ['design', 'writing', 'people'],
      path: {
        ms: ['Art electives; keep a sketchbook', 'Try free design tools', 'Enter school poster contests'],
        9: ['Art 1 / Digital Art', 'Start a portfolio folder', 'Join yearbook or newspaper design team'],
        10: ['Graphic Design or Photography elective', 'Learn UX basics: interview a user, sketch an app screen', 'Design for a club or local event'],
        11: ['AP Art & Design (2-D)', 'AP Computer Science Principles (for UX)', 'Enter Scholastic Art & Writing Awards'],
        12: ['Build a polished online portfolio', 'Summer art/design program', 'Apply to design / art schools or HCI programs'],
      },
      competitions: ['Scholastic Art & Writing Awards (MS & HS)', 'Congressional Art Competition', 'Doodle for Google', 'Yearbook / journalism design awards', 'Local art shows'],
      tasks: [
        { title: 'Sketchbook session: draw 5 thumbnails of one idea', skill: 'Drawing' },
        { title: 'Redesign a logo you see every day', skill: 'Design' },
        { title: 'Study a color palette and why it works', skill: 'Color' },
        { title: 'Recreate a poster layout in a design tool', skill: 'Tools' },
        { title: 'Sketch an app screen and test it on a friend', skill: 'UX' },
        { title: 'Add one piece to your portfolio', skill: 'Portfolio' },
      ],
    },
    {
      id: 'teacher', title: 'Teacher', emoji: '🍎',
      summary: 'Inspires and guides students to learn and grow.',
      traits: { S: 3, A: 1, C: 1 }, subjects: ['English', 'History', 'Math', 'Psychology'],
      keywords: ['teaching', 'kids', 'helping', 'tutoring', 'explaining', 'reading', 'coaching', 'babysitting'],
      skills: ['Explaining ideas clearly', 'Patience & empathy', 'Subject expertise', 'Organization'],
      domains: ['people', 'writing', 'math'],
      path: {
        ms: ['Help classmates in a subject you love', 'Join a reading buddy or peer program', 'Practice public speaking'],
        9: ['Pick a favorite subject to master', 'Volunteer tutoring', 'Join Future Educators club'],
        10: ['Tutor younger students regularly', 'Psychology elective', 'Camp counselor or coaching'],
        11: ['AP Psychology', 'AP in your favorite subject', 'Lead a study group or club'],
        12: ['Teacher cadet / education pathway course', 'Student-teach at an elementary school', 'Apply to education programs'],
      },
      competitions: ['Educators Rising competitions', 'Speech & debate', 'National History Day', 'Spelling / geography bees (MS)'],
      tasks: [
        { title: 'Explain a topic you know to someone younger', skill: 'Teaching' },
        { title: 'Make a one-page study guide for a topic', skill: 'Organization' },
        { title: 'Read about how people learn best', skill: 'Psychology' },
        { title: 'Practice a 2-minute talk out loud', skill: 'Speaking' },
        { title: 'Deepen your favorite subject for one session', skill: 'Expertise' },
        { title: 'Plan a fun 10-minute mini-lesson', skill: 'Planning' },
      ],
    },
    {
      id: 'entrepreneur', title: 'Entrepreneur', emoji: '🚀',
      summary: 'Starts businesses that solve problems and create jobs.',
      traits: { E: 3, A: 1, I: 1 }, subjects: ['Economics', 'English', 'Math', 'Computer Science'],
      keywords: ['business', 'money', 'selling', 'ideas', 'leader', 'startup', 'invent', 'lemonade', 'youtube', 'social media'],
      skills: ['Business & money basics', 'Persuasion & pitching', 'Creativity', 'Resilience'],
      domains: ['economics', 'people', 'writing'],
      path: {
        ms: ['Run a small business (bake sale, crafts, lawn care)', 'Learn money basics: saving, profit', 'Join student council'],
        9: ['Intro to Business / Personal Finance', 'Join DECA or FBLA', 'Read biographies of founders'],
        10: ['Start a real micro-business or club', 'Learn basic marketing & social media', 'Enter a pitch competition'],
        11: ['AP Microeconomics / Macroeconomics', 'AP Statistics', 'Lead a team project with a budget'],
        12: ['Grow your venture or launch a new one', 'Find a mentor / internship at a startup', 'Apply to business, economics, or CS programs'],
      },
      competitions: ['DECA', 'FBLA', 'Diamond Challenge for young entrepreneurs', 'Junior Achievement company program', 'Conrad Challenge', 'Economics Olympiad'],
      tasks: [
        { title: 'Write down 3 problems people have and a business idea for each', skill: 'Ideas' },
        { title: 'Learn a money concept: profit, cost, revenue', skill: 'Business' },
        { title: 'Practice a 60-second pitch out loud', skill: 'Pitching' },
        { title: 'Study how a famous company started', skill: 'Strategy' },
        { title: 'Make a simple budget for your idea', skill: 'Finance' },
        { title: 'Ask 3 people what they think of your idea', skill: 'Customers' },
      ],
    },
    {
      id: 'lawyer', title: 'Lawyer', emoji: '⚖️',
      summary: 'Defends people\'s rights, argues cases, and helps write fair rules.',
      traits: { E: 3, I: 2, C: 1 }, subjects: ['English', 'History', 'Government'],
      keywords: ['debate', 'arguing', 'justice', 'reading', 'writing', 'politics', 'fairness', 'history', 'speech'],
      skills: ['Reading & writing', 'Logical argument', 'Public speaking', 'Civics & history'],
      domains: ['civics', 'writing', 'logic'],
      path: {
        ms: ['Join debate or speech club', 'Read widely — news and novels', 'Model UN (if offered)'],
        9: ['Honors English', 'World History', 'Join Mock Trial or debate team'],
        10: ['AP World / US History', 'Student government', 'Write for the school newspaper'],
        11: ['AP US Government', 'AP English Language', 'Compete in Mock Trial / Model UN'],
        12: ['AP English Literature', 'Internship at a law office or legislator', 'Apply to political science, history, or English programs'],
      },
      competitions: ['Mock Trial', 'Speech & Debate (NSDA)', 'Model UN', 'We the People civics competition', 'National History Day', 'Essay contests'],
      tasks: [
        { title: 'Read a news story and write both sides of the argument', skill: 'Argument' },
        { title: 'Learn about a famous Supreme Court case', skill: 'Civics' },
        { title: 'Practice a 2-minute persuasive speech', skill: 'Speaking' },
        { title: 'Grammar and clear-writing practice', skill: 'Writing' },
        { title: 'Logic practice: spot the flaw in an argument', skill: 'Logic' },
        { title: 'Write a 1-paragraph persuasive essay', skill: 'Writing' },
      ],
    },
    {
      id: 'psychologist', title: 'Psychologist', emoji: '🧠',
      summary: 'Studies how people think and feel, and helps them with mental health.',
      traits: { S: 3, I: 2 }, subjects: ['Psychology', 'Biology', 'English', 'Math'],
      keywords: ['people', 'feelings', 'helping', 'mind', 'brain', 'listening', 'mental health', 'why people'],
      skills: ['Understanding people', 'Research & statistics', 'Biology of the brain', 'Listening & writing'],
      domains: ['people', 'science', 'stats'],
      path: {
        ms: ['Read about the brain and emotions', 'Peer mediation or kindness club', 'Practice journaling'],
        9: ['Biology', 'Join peer support / mentoring program', 'Read intro psychology books'],
        10: ['Psychology elective', 'Volunteer with kids or seniors', 'Do a small survey project'],
        11: ['AP Psychology', 'AP Statistics', 'Science fair project on behavior'],
        12: ['AP Biology', 'Research assistant / summer program', 'Apply to psychology or neuroscience programs'],
      },
      competitions: ['Brain Bee', 'Science fair (behavioral science)', 'Psychology essay contests', 'HOSA behavioral health events'],
      tasks: [
        { title: 'Learn about a famous psychology experiment', skill: 'Psychology' },
        { title: 'Study one part of the brain and what it does', skill: 'Neuroscience' },
        { title: 'Design a 5-question survey', skill: 'Research' },
        { title: 'Practice active listening in a conversation', skill: 'Listening' },
        { title: 'Read about a mental health topic', skill: 'Mental health' },
        { title: 'Statistics practice for research', skill: 'Statistics' },
      ],
    },
    {
      id: 'env-scientist', title: 'Environmental Scientist', emoji: '🌱',
      summary: 'Protects nature and fights climate change using science.',
      traits: { I: 3, R: 2, S: 1 }, subjects: ['Biology', 'Chemistry', 'Math'],
      keywords: ['nature', 'animals', 'outdoors', 'hiking', 'climate', 'plants', 'ocean', 'environment', 'gardening', 'camping'],
      skills: ['Biology & chemistry', 'Field work', 'Data analysis', 'Science communication'],
      domains: ['science', 'stats', 'writing'],
      path: {
        ms: ['Join an eco / garden club', 'Do a backyard nature survey', 'Science Olympiad ecology events'],
        9: ['Biology', 'Environmental club', 'Volunteer for a park clean-up'],
        10: ['Chemistry', 'Start a recycling or energy project at school', 'Citizen-science project (iNaturalist, bird counts)'],
        11: ['AP Environmental Science', 'AP Statistics', 'Envirothon competition'],
        12: ['AP Biology or Chemistry', 'Summer field research program', 'Apply to environmental science programs'],
      },
      competitions: ['Envirothon', 'Science Olympiad', 'Stockholm Junior Water Prize', 'President\'s Environmental Youth Award', 'Science fair (ISEF)'],
      tasks: [
        { title: 'Identify 5 plants or animals near you', skill: 'Field work' },
        { title: 'Learn about the water or carbon cycle', skill: 'Science' },
        { title: 'Read about a climate solution', skill: 'Climate' },
        { title: 'Graph local weather data for a week', skill: 'Data' },
        { title: 'Write a short article about a local environmental issue', skill: 'Communication' },
        { title: 'Ecology olympiad-style practice', skill: 'Ecology' },
      ],
    },
    {
      id: 'financial-analyst', title: 'Financial Analyst', emoji: '💹',
      summary: 'Helps people and companies make smart decisions with money.',
      traits: { C: 3, I: 2, E: 1 }, subjects: ['Math', 'Economics', 'Computer Science'],
      keywords: ['money', 'stocks', 'numbers', 'business', 'saving', 'math', 'spreadsheets', 'economics'],
      skills: ['Math & statistics', 'Economics', 'Spreadsheets', 'Careful decision making'],
      domains: ['economics', 'math', 'stats'],
      path: {
        ms: ['Track your own allowance / savings', 'Get ahead in math', 'Join a stock market simulation game'],
        9: ['Personal Finance course', 'Algebra 2', 'Join FBLA or investment club'],
        10: ['Learn spreadsheets (formulas, charts)', 'Pre-Calculus', 'Economics elective'],
        11: ['AP Macro / Microeconomics', 'AP Statistics', 'Compete in the Wharton Global Youth Investment Competition'],
        12: ['AP Calculus', 'Internship at a bank or local business', 'Apply to finance, economics, or accounting programs'],
      },
      competitions: ['National Economics Challenge', 'Wharton Global Youth Investment Competition', 'FBLA', 'Stock Market Game (SIFMA)', 'Economics Olympiad'],
      tasks: [
        { title: 'Learn a money concept: interest and compounding', skill: 'Finance' },
        { title: 'Build a spreadsheet budget', skill: 'Spreadsheets' },
        { title: 'Follow one company in the news and take notes', skill: 'Analysis' },
        { title: 'Percent and ratio practice', skill: 'Math' },
        { title: 'Read about supply and demand', skill: 'Economics' },
        { title: 'Compare two savings plans and pick the better one', skill: 'Decisions' },
      ],
    },
    {
      id: 'journalist', title: 'Journalist / Writer', emoji: '📰',
      summary: 'Discovers and tells true stories that keep people informed.',
      traits: { A: 2, E: 2, S: 1, I: 1 }, subjects: ['English', 'History', 'Government'],
      keywords: ['writing', 'reading', 'stories', 'news', 'books', 'blog', 'podcast', 'video', 'interviewing', 'photography'],
      skills: ['Writing', 'Research & fact-checking', 'Interviewing', 'Current events'],
      domains: ['writing', 'civics', 'people'],
      path: {
        ms: ['Keep a daily journal', 'Write for a school newsletter', 'Read a news site for kids daily'],
        9: ['Honors English', 'Join the school newspaper or yearbook', 'Start a blog or podcast'],
        10: ['Journalism elective', 'Interview someone in your community', 'Enter writing contests'],
        11: ['AP English Language', 'AP US History', 'Become an editor on the school paper'],
        12: ['AP English Literature', 'Summer journalism program', 'Apply to journalism or communications programs'],
      },
      competitions: ['Scholastic Art & Writing Awards', 'NYT Learning Network contests', 'JEA / NSPA journalism awards', 'National History Day', 'Speech & debate'],
      tasks: [
        { title: 'Write a 200-word news story about your school or town', skill: 'Writing' },
        { title: 'Fact-check a claim you saw online', skill: 'Research' },
        { title: 'Prepare 5 interview questions for someone', skill: 'Interviewing' },
        { title: 'Read a news article and summarize it in 3 sentences', skill: 'Current events' },
        { title: 'Grammar and style practice', skill: 'Writing' },
        { title: 'Edit something you wrote earlier', skill: 'Editing' },
      ],
    },
    {
      id: 'architect', title: 'Architect', emoji: '🏛️',
      summary: 'Designs buildings and spaces that are beautiful, safe, and useful.',
      traits: { A: 2, R: 2, I: 1, C: 1 }, subjects: ['Art', 'Math', 'Physics'],
      keywords: ['drawing', 'buildings', 'design', 'lego', 'minecraft', 'houses', 'cities', 'art', 'building', 'sketching'],
      skills: ['Drawing & design', 'Geometry & physics', '3D modeling', 'Creative problem solving'],
      domains: ['design', 'math', 'science'],
      path: {
        ms: ['Sketch buildings around you', 'Build models (LEGO, Minecraft, cardboard)', 'Get ahead in geometry'],
        9: ['Geometry', 'Art 1 / Drafting', 'Learn a free 3D tool (SketchUp, Tinkercad)'],
        10: ['Algebra 2', 'Architecture or engineering design elective', 'Visit buildings and take notes'],
        11: ['AP Physics 1', 'AP Art & Design', 'Enter an architecture design competition'],
        12: ['AP Calculus', 'Summer architecture program', 'Apply to architecture programs (with portfolio)'],
      },
      competitions: ['National Design Competition (ACE Mentor)', 'Future City Competition (MS)', 'Scholastic Art Awards (architecture)', 'SkillsUSA architectural drafting'],
      tasks: [
        { title: 'Sketch a room or building from real life', skill: 'Drawing' },
        { title: 'Geometry practice: area and volume', skill: 'Math' },
        { title: 'Model a small house in a 3D tool', skill: '3D modeling' },
        { title: 'Study a famous building and why it works', skill: 'History' },
        { title: 'Design your dream bedroom floor plan', skill: 'Design' },
        { title: 'Learn how bridges and beams carry weight', skill: 'Physics' },
      ],
    },
    {
      id: 'nurse', title: 'Nurse', emoji: '💉',
      summary: 'Cares for patients every day and is the heart of every hospital.',
      traits: { S: 3, R: 2, C: 1 }, subjects: ['Biology', 'Chemistry', 'Psychology', 'PE / Health'],
      keywords: ['helping', 'health', 'caring', 'babysitting', 'hospital', 'biology', 'people', 'first aid'],
      skills: ['Biology & health science', 'Compassion & communication', 'Staying calm under pressure', 'Careful attention to detail'],
      domains: ['science', 'people', 'math'],
      path: {
        ms: ['Health and science electives', 'Learn first aid', 'Help care for family members or pets'],
        9: ['Biology', 'Health class', 'Join HOSA'],
        10: ['Chemistry', 'CPR certification', 'Volunteer at a senior center or hospital'],
        11: ['AP Biology or Anatomy & Physiology', 'AP Psychology', 'Certified Nursing Assistant (CNA) course if available'],
        12: ['Medical terminology / health science pathway', 'Shadow a nurse', 'Apply to BSN nursing programs'],
      },
      competitions: ['HOSA competitive events', 'Science Olympiad (anatomy)', 'Red Cross youth programs', 'Health science fair projects'],
      tasks: [
        { title: 'Learn about a body system and how to keep it healthy', skill: 'Health science' },
        { title: 'Practice a first-aid scenario (step by step)', skill: 'First aid' },
        { title: 'Medical vocabulary flashcards', skill: 'Terminology' },
        { title: 'Read about a day in the life of a nurse', skill: 'Career' },
        { title: 'Dosage math: ratios and units practice', skill: 'Math' },
        { title: 'Practice calm, kind communication', skill: 'Communication' },
      ],
    },
  ];

  const REFLECT_PROMPTS = [
    'What did you learn today, and how does it connect to becoming a {career}?',
    'What was the hardest part of today, and how did you push through?',
    'Explain one thing you practiced today as if teaching a younger student.',
    'What mistake did you make today and what will you do differently next time?',
    'What is one question you still have after today? How could you find the answer?',
    'Which skill improved most this week? Give an example.',
    'What would a {career} find interesting about what you worked on today?',
  ];

  const DOMAINS = {
    math: { name: 'Math', emoji: '➗' },
    stats: { name: 'Statistics', emoji: '📈' },
    logic: { name: 'Logic & Patterns', emoji: '🧩' },
    coding: { name: 'Coding', emoji: '👩‍💻' },
    science: { name: 'Science', emoji: '🔬' },
    writing: { name: 'Writing & Grammar', emoji: '✍️' },
    economics: { name: 'Money & Business', emoji: '💰' },
    people: { name: 'People & Psychology', emoji: '🤝' },
    design: { name: 'Design', emoji: '🎨' },
    civics: { name: 'Civics & Law', emoji: '🏛️' },
  };

  // Static question banks: [question, [choices], correctIndex, level(1-3)]
  const BANK = {
    coding: [
      ['What does print(2 + 3 * 4) show in Python?', ['20', '14', '24', '9'], 1, 1],
      ['Which keyword usually starts a loop?', ['for', 'if', 'return', 'class'], 0, 1],
      ['What type of value is "hello"?', ['String (text)', 'Integer', 'Boolean', 'Decimal'], 0, 1],
      ['x = [4, 7, 9]. What is len(x)?', ['3', '9', '2', '20'], 0, 2],
      ['In most languages, what does == do?', ['Checks if two values are equal', 'Stores a value', 'Adds two numbers', 'Ends a line'], 0, 2],
      ['In Python, what is 17 // 5?', ['3', '3.4', '2', '12'], 0, 2],
      ['Binary search on 1,024 sorted items needs at most about how many checks?', ['10', '512', '1024', '100'], 0, 3],
      ['Which data structure is Last-In, First-Out?', ['Stack', 'Queue', 'Linked list', 'Hash map'], 0, 3],
      ['Looping once over n items takes what time?', ['O(n)', 'O(1)', 'O(n²)', 'O(log n)'], 0, 3],
    ],
    science: [
      ['Which part of the cell makes most of its energy?', ['Mitochondria', 'Nucleus', 'Cell wall', 'Ribosome'], 0, 1],
      ['Which gas do plants take in for photosynthesis?', ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'], 0, 1],
      ['Which planet is closest to the Sun?', ['Mercury', 'Venus', 'Earth', 'Mars'], 0, 1],
      ['What is the unit of force?', ['Newton', 'Joule', 'Watt', 'Gram'], 0, 2],
      ['A solution with pH 3 is…', ['Acidic', 'Basic', 'Neutral', 'Salty'], 0, 2],
      ['DNA has the shape of a…', ['Double helix', 'Single ring', 'Cube', 'Flat sheet'], 0, 2],
      ['A 2 kg object accelerates at 3 m/s². What is the net force?', ['6 N', '1.5 N', '5 N', '9 N'], 0, 3],
      ['Which organ produces insulin?', ['Pancreas', 'Liver', 'Kidney', 'Stomach'], 0, 3],
      ['In an ecosystem, organisms that make their own food are…', ['Producers', 'Consumers', 'Decomposers', 'Predators'], 0, 3],
    ],
    writing: [
      ['Choose the correct word: "___ going to the park."', ["They're", 'Their', 'There', 'Theyre'], 0, 1],
      ['Which word means almost the same as "rapid"?', ['Fast', 'Quiet', 'Heavy', 'Late'], 0, 1],
      ['Which is a complete sentence?', ['The cat slept on the mat.', 'Running down the street.', 'Because it rained.', 'The big red'], 0, 1],
      ['Which word is an adverb? "She quickly solved the problem."', ['quickly', 'She', 'solved', 'problem'], 0, 2],
      ['Choose the correct word: "The dog wagged ___ tail."', ['its', "it's", 'its\'', 'it is'], 0, 2],
      ['What is a thesis statement?', ['The main argument of an essay', 'The title', 'A list of sources', 'The last sentence of every paragraph'], 0, 2],
      ['Which sentence uses a semicolon correctly?', ['I studied hard; I passed the test.', 'I studied; hard for the test.', 'Because; I studied.', 'I; studied hard.'], 0, 3],
      ['"Everyone is doing it, so it must be right" is which fallacy?', ['Bandwagon', 'Straw man', 'Ad hominem', 'Red herring'], 0, 3],
      ['Which sentence is in active voice?', ['The team won the game.', 'The game was won by the team.', 'The game had been won.', 'Winning was done.'], 0, 3],
    ],
    economics: [
      ['If demand goes up and supply stays the same, price usually…', ['Goes up', 'Goes down', 'Stays the same', 'Becomes zero'], 0, 1],
      ['Money a business earns from sales is called…', ['Revenue', 'Debt', 'Tax', 'Loan'], 0, 1],
      ['Saving $15 a week for 8 weeks gives you…', ['$120', '$23', '$100', '$150'], 0, 1],
      ['Profit equals…', ['Revenue minus costs', 'Costs minus revenue', 'Revenue plus costs', 'Price times zero'], 0, 2],
      ['Opportunity cost is…', ['The next-best choice you give up', 'The price on the tag', 'A store discount', 'A tax'], 0, 2],
      ['$200 at 5% simple interest for 1 year earns…', ['$10', '$5', '$20', '$100'], 0, 2],
      ['$1,000 at 10% interest compounded yearly is worth what after 2 years?', ['$1,210', '$1,200', '$1,100', '$1,020'], 0, 3],
      ['Inflation means…', ['Prices in general rise over time', 'Prices fall', 'Wages are frozen', 'Stocks always rise'], 0, 3],
      ['Revenue $50k and costs $40k. What is the profit margin?', ['20%', '25%', '10%', '80%'], 0, 3],
    ],
    people: [
      ['Which is part of active listening?', ['Repeating back what you heard', 'Checking your phone', 'Interrupting with your story', 'Changing the topic'], 0, 1],
      ['Empathy means…', ['Understanding how someone else feels', 'Feeling sorry for yourself', 'Always agreeing', 'Ignoring feelings'], 0, 1],
      ['Good feedback is…', ['Specific and kind', 'Vague and harsh', 'Only about the person', 'Given in public to embarrass'], 0, 1],
      ['Which is an open-ended question?', ['How did you feel about the game?', 'Did you win?', 'Is it Monday?', 'Are you 13?'], 0, 2],
      ['Body language is a type of…', ['Nonverbal communication', 'Written communication', 'Sign language only', 'Math'], 0, 2],
      ['The base of Maslow\'s hierarchy of needs is…', ['Physiological needs (food, sleep)', 'Self-actualization', 'Esteem', 'Friendship'], 0, 2],
      ['Confirmation bias is…', ['Favoring info that supports what you already believe', 'Confirming facts carefully', 'Being unsure', 'A memory trick'], 0, 3],
      ['In an experiment, the group that gets no treatment is the…', ['Control group', 'Test group', 'Variable group', 'Bias group'], 0, 3],
      ['The placebo effect is…', ['Feeling better because you believe a treatment works', 'A side effect of medicine', 'A type of virus', 'Forgetting things'], 0, 3],
    ],
    design: [
      ['Traditional primary colors are…', ['Red, yellow, blue', 'Green, orange, purple', 'Black, white, gray', 'Pink, teal, gold'], 0, 1],
      ['Which image format scales to any size without getting blurry?', ['SVG (vector)', 'JPG', 'PNG', 'GIF'], 0, 1],
      ['"White space" in design is…', ['Empty space that makes things easier to read', 'A mistake', 'Only the color white', 'Wasted paper'], 0, 1],
      ['The complementary color of blue is…', ['Orange', 'Green', 'Purple', 'Red'], 0, 2],
      ['The rule of thirds divides an image into…', ['A 3×3 grid', '3 colors', '3 fonts', '3 layers'], 0, 2],
      ['Kerning adjusts…', ['The space between letters', 'The color of text', 'Line height', 'Image size'], 0, 2],
      ['Minimum contrast ratio for normal text (WCAG AA) is…', ['4.5 : 1', '1 : 1', '2 : 1', '10 : 1'], 0, 3],
      ['Gestalt "proximity" means…', ['Items close together look like a group', 'Big items look important', 'Colors blend', 'Text must be centered'], 0, 3],
      ['In UX, a "persona" is…', ['A fictional profile of a typical user', 'A logo', 'A font family', 'A coding language'], 0, 3],
    ],
    civics: [
      ['How many branches does the U.S. federal government have?', ['3', '2', '4', '5'], 0, 1],
      ['Which branch makes laws?', ['Legislative (Congress)', 'Executive', 'Judicial', 'Military'], 0, 1],
      ['The first 10 amendments to the U.S. Constitution are called…', ['The Bill of Rights', 'The Preamble', 'The Articles', 'The Federalist Papers'], 0, 1],
      ['Freedom of speech is protected by which amendment?', ['First', 'Second', 'Fifth', 'Tenth'], 0, 2],
      ['Judicial review lets courts…', ['Strike down unconstitutional laws', 'Write new laws', 'Elect the president', 'Collect taxes'], 0, 2],
      ['In a criminal trial, who decides guilty or not guilty?', ['The jury (or judge)', 'The police', 'The lawyer', 'The governor'], 0, 2],
      ['Legal "precedent" is…', ['An earlier court decision that guides future cases', 'A new law', 'A type of jury', 'A courtroom'], 0, 3],
      ['The burden of proof in a criminal case is…', ['Beyond a reasonable doubt', 'More likely than not', 'Any evidence', 'A confession'], 0, 3],
      ['Marbury v. Madison (1803) established…', ['Judicial review', 'Freedom of religion', 'The right to vote', 'The Electoral College'], 0, 3],
    ],
  };

  const BADGES = [
    { id: 'explorer', emoji: '🧭', name: 'Self-Explorer', desc: 'Finished the personality test.' },
    { id: 'pathfinder', emoji: '🗺️', name: 'Pathfinder', desc: 'Picked a career path.' },
    { id: 'first-step', emoji: '👣', name: 'First Step', desc: 'Completed your first task.' },
    { id: 'perfect-day', emoji: '🌟', name: 'Perfect Day', desc: 'Finished every task in a day.' },
    { id: 'streak-3', emoji: '🔥', name: 'On Fire', desc: '3-day streak.' },
    { id: 'streak-7', emoji: '⚡', name: 'Unstoppable', desc: '7-day streak.' },
    { id: 'streak-30', emoji: '🏔️', name: 'Summit', desc: '30-day streak.' },
    { id: 'quiz-whiz', emoji: '🎯', name: 'Quiz Whiz', desc: 'Scored 100% on a practice set.' },
    { id: 'level-3', emoji: '📈', name: 'Rising Star', desc: 'Reached skill level 3 in any subject.' },
    { id: 'level-5', emoji: '🏆', name: 'Olympiad Ready', desc: 'Reached skill level 5 (competition level).' },
    { id: 'deep-focus', emoji: '🧘', name: 'Deep Focus', desc: '25+ minute focus session with zero distractions.' },
    { id: 'thinker', emoji: '💭', name: 'Deep Thinker', desc: '5 reflections accepted.' },
    { id: 'milestone', emoji: '🎖️', name: 'Go-Getter', desc: 'Completed a real-world milestone (competition, club, course…).' },
    { id: 'honest', emoji: '🛡️', name: 'Honest Hustler', desc: '15 tasks done with integrity score 95+.' },
    { id: 'xp-1000', emoji: '💎', name: 'XP Collector', desc: 'Earned 1,000 XP.' },
  ];

  const LEVEL_TITLES = ['Novice', 'Apprentice', 'Explorer', 'Achiever', 'Trailblazer', 'Expert', 'Champion', 'Legend'];

  return { TRAITS, QUESTIONS, SUBJECTS, STAGES, CAREERS, REFLECT_PROMPTS, DOMAINS, BANK, BADGES, LEVEL_TITLES };
})();
