// Python exercises. The student writes a function; the app runs it in the browser against the tests.
// `a` = arguments, `e` = expected result. The first two tests are shown; the rest are hidden (so students can't hard-code answers).
// careers: ['*'] = general practice, otherwise the careers whose "job" this exercise belongs to.
window.PF_EXERCISES = [
  // ---------- core Python skills (levels 1-5) ----------
  { id: 'py-greet', level: 1, careers: ['*'], title: 'Greet someone', fn: 'greet', sig: 'name',
    story: 'Every app greets its users. Write a function that makes a greeting.',
    task: 'Write greet(name) that returns the text "Hello, " followed by the name and an exclamation mark.',
    learn: 'You can join text with +. A function sends an answer back with return.\n\ndef shout(word):\n    return word + "!"\n\nshout("hi") gives "hi!"',
    starter: 'def greet(name):\n    # return the greeting\n    pass\n',
    hints: ['Start with the text "Hello, " then add name.', 'return "Hello, " + name + "!"'],
    solution: 'def greet(name):\n    return "Hello, " + name + "!"\n',
    tests: [{ a: ['Maya'], e: 'Hello, Maya!' }, { a: ['Sam'], e: 'Hello, Sam!' }, { a: [''], e: 'Hello, !' }, { a: ['Dr. Lee'], e: 'Hello, Dr. Lee!' }] },
  { id: 'py-area', level: 1, careers: ['*'], title: 'Area of a rectangle', fn: 'area', sig: 'width, height',
    story: 'A builder needs the area of walls to know how much paint to buy.',
    task: 'Write area(width, height) that returns width times height.',
    learn: 'Use * to multiply. Arguments are the values you pass in.\n\ndef double(x):\n    return x * 2',
    starter: 'def area(width, height):\n    pass\n',
    hints: ['Multiply the two numbers.', 'return width * height'],
    solution: 'def area(width, height):\n    return width * height\n',
    tests: [{ a: [3, 4], e: 12 }, { a: [10, 2.5], e: 25 }, { a: [0, 5], e: 0 }, { a: [7, 7], e: 49 }] },
  { id: 'py-parity', level: 2, careers: ['*'], title: 'Even or odd', fn: 'parity', sig: 'n',
    story: 'Many programs need to split things into two groups, like alternating row colors.',
    task: 'Write parity(n) that returns the text "even" if n is even and "odd" if it is odd.',
    learn: 'The remainder operator % gives what is left after dividing: 7 % 2 is 1. An if statement chooses between actions:\n\nif x > 5:\n    return "big"\nreturn "small"',
    starter: 'def parity(n):\n    pass\n',
    hints: ['An even number has remainder 0 when divided by 2.', 'if n % 2 == 0:\n    return "even"\nreturn "odd"'],
    solution: 'def parity(n):\n    if n % 2 == 0:\n        return "even"\n    return "odd"\n',
    tests: [{ a: [4], e: 'even' }, { a: [7], e: 'odd' }, { a: [0], e: 'even' }, { a: [-3], e: 'odd' }, { a: [100], e: 'even' }] },
  { id: 'py-sum-to', level: 2, careers: ['*'], title: 'Add up to n', fn: 'sum_to', sig: 'n',
    story: 'A teacher wants to total the numbers 1 to n without a calculator.',
    task: 'Write sum_to(n) that returns 1 + 2 + 3 + … + n. Use a loop.',
    learn: 'A for loop with range(1, n + 1) visits 1, 2, …, n. Keep a running total:\n\ntotal = 0\nfor i in range(1, 4):\n    total = total + i\n# total is now 6',
    starter: 'def sum_to(n):\n    total = 0\n    # loop here\n    return total\n',
    hints: ['range(1, n + 1) gives 1 up to n.', 'for i in range(1, n + 1):\n    total = total + i'],
    solution: 'def sum_to(n):\n    total = 0\n    for i in range(1, n + 1):\n        total = total + i\n    return total\n',
    tests: [{ a: [5], e: 15 }, { a: [1], e: 1 }, { a: [100], e: 5050 }, { a: [0], e: 0 }] },
  { id: 'py-vowels', level: 3, careers: ['*'], title: 'Count the vowels', fn: 'count_vowels', sig: 'text',
    story: 'A word-game app scores words by how many vowels they have.',
    task: 'Write count_vowels(text) that returns how many letters in text are vowels (a, e, i, o, u). Ignore capital letters: "A" counts too.',
    learn: 'You can loop over the letters in a string, and text.lower() makes everything lowercase. The in keyword checks membership:\n\nif letter in "aeiou":\n    ...',
    starter: 'def count_vowels(text):\n    count = 0\n    # loop over each letter\n    return count\n',
    hints: ['Use text.lower() first so "A" and "a" are the same.', 'for letter in text.lower():\n    if letter in "aeiou":\n        count = count + 1'],
    solution: 'def count_vowels(text):\n    count = 0\n    for letter in text.lower():\n        if letter in "aeiou":\n            count = count + 1\n    return count\n',
    tests: [{ a: ['banana'], e: 3 }, { a: ['rhythm'], e: 0 }, { a: ['AEIOU'], e: 5 }, { a: ['Hello World'], e: 3 }, { a: [''], e: 0 }] },
  { id: 'py-average', level: 3, careers: ['*'], title: 'Average of a list', fn: 'average', sig: 'nums',
    story: 'A gradebook needs to compute the average of a list of scores.',
    task: 'Write average(nums) that returns the sum divided by how many numbers there are. If the list is empty, return 0.',
    learn: 'sum(list) adds everything up and len(list) counts the items.\n\nscores = [2, 4, 6]\nsum(scores) / len(scores)   # 4.0\n\nDividing by zero crashes, so check for an empty list first.',
    starter: 'def average(nums):\n    pass\n',
    hints: ['Check for an empty list first: if len(nums) == 0.', 'if len(nums) == 0:\n    return 0\nreturn sum(nums) / len(nums)'],
    solution: 'def average(nums):\n    if len(nums) == 0:\n        return 0\n    return sum(nums) / len(nums)\n',
    tests: [{ a: [[2, 4, 6]], e: 4 }, { a: [[10]], e: 10 }, { a: [[]], e: 0 }, { a: [[1, 2]], e: 1.5 }] },
  { id: 'py-wordcount', level: 4, careers: ['*'], title: 'Word counter', fn: 'word_count', sig: 'text',
    story: 'Search engines count how often words appear. You will build the heart of that.',
    task: 'Write word_count(text) that returns a dictionary mapping each word (lowercase) to how many times it appears. Words are separated by spaces.',
    learn: 'A dictionary stores pairs: counts = {"a": 2}. text.split() turns text into a list of words. To count:\n\ncounts = {}\nfor w in words:\n    counts[w] = counts.get(w, 0) + 1',
    starter: 'def word_count(text):\n    counts = {}\n    # fill counts\n    return counts\n',
    hints: ['Use text.lower().split() to get lowercase words.', 'counts[w] = counts.get(w, 0) + 1 adds 1 to the old count (or starts at 0).'],
    solution: 'def word_count(text):\n    counts = {}\n    for w in text.lower().split():\n        counts[w] = counts.get(w, 0) + 1\n    return counts\n',
    tests: [{ a: ['a b a'], e: { a: 2, b: 1 } }, { a: ['Go go GO stop'], e: { go: 3, stop: 1 } }, { a: [''], e: {} }, { a: ['x'], e: { x: 1 } }] },
  { id: 'py-fizzbuzz', level: 4, careers: ['*'], title: 'FizzBuzz', fn: 'fizzbuzz', sig: 'n',
    story: 'FizzBuzz is a classic interview question. Every software engineer meets it once.',
    task: 'Write fizzbuzz(n) that returns a list of text items for the numbers 1 to n: "Fizz" if the number divides by 3, "Buzz" if it divides by 5, "FizzBuzz" if it divides by both, otherwise the number as text like "7".',
    learn: 'Build a list with append and use str(x) to turn a number into text. Check the "both" case first, or it will never run.\n\nresult = []\nresult.append("a")',
    starter: 'def fizzbuzz(n):\n    result = []\n    # loop from 1 to n\n    return result\n',
    hints: ['Check divisibility by 15 (both) before 3 and 5.', 'if i % 15 == 0: ... elif i % 3 == 0: ... elif i % 5 == 0: ... else: str(i)'],
    solution: 'def fizzbuzz(n):\n    result = []\n    for i in range(1, n + 1):\n        if i % 15 == 0:\n            result.append("FizzBuzz")\n        elif i % 3 == 0:\n            result.append("Fizz")\n        elif i % 5 == 0:\n            result.append("Buzz")\n        else:\n            result.append(str(i))\n    return result\n',
    tests: [{ a: [5], e: ['1', '2', 'Fizz', '4', 'Buzz'] }, { a: [1], e: ['1'] }, { a: [15], e: ['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz'] }, { a: [0], e: [] }] },
  { id: 'py-prime', level: 5, careers: ['*'], title: 'Is it prime?', fn: 'is_prime', sig: 'n',
    story: 'Prime numbers keep your online passwords safe. Test whether a number is prime.',
    task: 'Write is_prime(n) that returns True if n is a prime number and False if not. (1 is not prime.)',
    learn: 'A prime is only divisible by 1 and itself. You only need to test divisors up to the square root of n. Return False as soon as you find a divisor.',
    starter: 'def is_prime(n):\n    pass\n',
    hints: ['Numbers below 2 are not prime.', 'for d in range(2, int(n ** 0.5) + 1):\n    if n % d == 0:\n        return False\nreturn True'],
    solution: 'def is_prime(n):\n    if n < 2:\n        return False\n    for d in range(2, int(n ** 0.5) + 1):\n        if n % d == 0:\n            return False\n    return True\n',
    tests: [{ a: [7], e: true }, { a: [10], e: false }, { a: [1], e: false }, { a: [97], e: true }, { a: [2], e: true }, { a: [91], e: false }] },
  { id: 'py-binsearch', level: 5, careers: ['*'], title: 'Binary search', fn: 'binary_search', sig: 'items, target',
    story: 'Phone contacts and search bars find things in sorted lists by cutting the list in half again and again.',
    task: 'Write binary_search(items, target) for a sorted list. Return the index where target is found, or -1 if it is not there.',
    learn: 'Keep two markers, low and high. Look at the middle. If the middle is too big, move high down; if too small, move low up.\n\nmid = (low + high) // 2',
    starter: 'def binary_search(items, target):\n    low = 0\n    high = len(items) - 1\n    # keep searching while low <= high\n    return -1\n',
    hints: ['while low <= high: look at mid = (low + high) // 2.', 'If items[mid] == target return mid; if it is less than target set low = mid + 1; otherwise high = mid - 1.'],
    solution: 'def binary_search(items, target):\n    low = 0\n    high = len(items) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if items[mid] == target:\n            return mid\n        if items[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1\n',
    tests: [{ a: [[1, 3, 5, 7, 9], 7], e: 3 }, { a: [[1, 3, 5], 4], e: -1 }, { a: [[2], 2], e: 0 }, { a: [[], 1], e: -1 }, { a: [[1, 2, 3, 4, 5, 6], 1], e: 0 }, { a: [[1, 2, 3, 4, 5, 6], 6], e: 5 }] },

  // ---------- Data Scientist ----------
  { id: 'ds-class-average', level: 2, careers: ['data-scientist'], title: 'Class average', fn: 'class_average', sig: 'scores',
    story: 'You are a data scientist for a school. First job: report the average test score, rounded to one decimal place.',
    task: 'Write class_average(scores) that returns the average of the list, rounded to 1 decimal place.',
    learn: 'average = sum(scores) / len(scores). round(number, 1) keeps one decimal place:\n\nround(85.678, 1)   # 85.7',
    starter: 'def class_average(scores):\n    pass\n',
    hints: ['Divide the sum by the number of scores.', 'return round(sum(scores) / len(scores), 1)'],
    solution: 'def class_average(scores):\n    return round(sum(scores) / len(scores), 1)\n',
    tests: [{ a: [[90, 80, 70]], e: 80 }, { a: [[85, 92, 78, 88]], e: 85.8 }, { a: [[100]], e: 100 }, { a: [[1, 2, 2]], e: 1.7 }] },
  { id: 'ds-median', level: 3, careers: ['data-scientist'], title: 'Find the median', fn: 'median', sig: 'values',
    story: 'Averages get pulled around by extreme numbers. Data scientists often report the median (the middle value) too.',
    task: 'Write median(values) that returns the median of a list. With an even number of values, return the average of the two middle values.',
    learn: 'sorted(values) returns a sorted copy. For a list of length n, the middle index is n // 2.\n\nodd length 5 → index 2\neven length 4 → average of indexes 1 and 2',
    starter: 'def median(values):\n    pass\n',
    hints: ['First sort the list: s = sorted(values).', 'If len(s) is odd return s[len(s) // 2]; if even, average s[len(s)//2 - 1] and s[len(s)//2].'],
    solution: 'def median(values):\n    s = sorted(values)\n    n = len(s)\n    if n % 2 == 1:\n        return s[n // 2]\n    return (s[n // 2 - 1] + s[n // 2]) / 2\n',
    tests: [{ a: [[3, 1, 2]], e: 2 }, { a: [[4, 1, 3, 2]], e: 2.5 }, { a: [[7]], e: 7 }, { a: [[5, 1, 9, 3, 7]], e: 5 }, { a: [[10, 20]], e: 15 }] },
  { id: 'ds-above-average', level: 3, careers: ['data-scientist'], title: 'Above average', fn: 'above_average', sig: 'values',
    story: 'Your boss wants to know which days had more website visitors than usual.',
    task: 'Write above_average(values) that returns a list of the values that are greater than the average, in the original order.',
    learn: 'Compute the average first, then build a new list with only the values that pass a test:\n\nbig = []\nfor v in values:\n    if v > 10:\n        big.append(v)',
    starter: 'def above_average(values):\n    pass\n',
    hints: ['Work out avg = sum(values) / len(values) first.', 'Loop through values and append those with v > avg.'],
    solution: 'def above_average(values):\n    avg = sum(values) / len(values)\n    result = []\n    for v in values:\n        if v > avg:\n            result.append(v)\n    return result\n',
    tests: [{ a: [[1, 2, 3, 10]], e: [10] }, { a: [[5, 5, 5]], e: [] }, { a: [[1, 9]], e: [9] }, { a: [[2, 4, 6, 8]], e: [6, 8] }] },
  { id: 'ds-mode', level: 4, careers: ['data-scientist'], title: 'Most common value (mode)', fn: 'mode', sig: 'values',
    story: 'Which shoe size sells the most? That is the mode, the value that appears most often.',
    task: 'Write mode(values) that returns the value that appears most often. If there is a tie, return the smallest of the tied values.',
    learn: 'Count with a dictionary (counts[v] = counts.get(v, 0) + 1), then find the highest count. max(list) and min(list) find the biggest and smallest items.',
    starter: 'def mode(values):\n    counts = {}\n    # count each value\n    pass\n',
    hints: ['Count each value in a dictionary, then find the biggest count with max(counts.values()).', 'Collect all values whose count equals the biggest count, then return the min of those.'],
    solution: 'def mode(values):\n    counts = {}\n    for v in values:\n        counts[v] = counts.get(v, 0) + 1\n    best = max(counts.values())\n    tied = [v for v in counts if counts[v] == best]\n    return min(tied)\n',
    tests: [{ a: [[1, 2, 2, 3]], e: 2 }, { a: [[4, 4, 5, 5]], e: 4 }, { a: [[9]], e: 9 }, { a: [[3, 1, 1, 3, 2]], e: 1 }] },

  // ---------- Software Engineer ----------
  { id: 'se-reverse', level: 2, careers: ['software-engineer'], title: 'Reverse the text', fn: 'reverse_text', sig: 'text',
    story: 'You are building a text toy for a mobile app. First feature: flip text backwards.',
    task: 'Write reverse_text(text) that returns the text written backwards.',
    learn: 'Strings can be sliced: text[::-1] gives the text backwards. Or build it with a loop going through the letters.',
    starter: 'def reverse_text(text):\n    pass\n',
    hints: ['A slice with step -1 reverses a string.', 'return text[::-1]'],
    solution: 'def reverse_text(text):\n    return text[::-1]\n',
    tests: [{ a: ['abc'], e: 'cba' }, { a: ['Python'], e: 'nohtyP' }, { a: [''], e: '' }, { a: ['racecar'], e: 'racecar' }] },
  { id: 'se-palindrome', level: 3, careers: ['software-engineer'], title: 'Palindrome checker', fn: 'is_palindrome', sig: 'text',
    story: 'A word game needs to know whether a phrase reads the same forwards and backwards.',
    task: 'Write is_palindrome(text) that returns True if the text is a palindrome and False otherwise. Ignore spaces and capital letters.',
    learn: 'text.lower() makes lowercase, and text.replace(" ", "") removes spaces. Compare the cleaned text with its reverse (text[::-1]).',
    starter: 'def is_palindrome(text):\n    pass\n',
    hints: ['Clean the text: lowercase and remove spaces.', 'cleaned = text.lower().replace(" ", "")\nreturn cleaned == cleaned[::-1]'],
    solution: 'def is_palindrome(text):\n    cleaned = text.lower().replace(" ", "")\n    return cleaned == cleaned[::-1]\n',
    tests: [{ a: ['level'], e: true }, { a: ['hello'], e: false }, { a: ['A man a plan a canal Panama'], e: true }, { a: ['Never odd or even'], e: true }, { a: [''], e: true }] },
  { id: 'se-password', level: 3, careers: ['software-engineer'], title: 'Password strength', fn: 'strong_password', sig: 'password',
    story: 'Your login screen should reject weak passwords.',
    task: 'Write strong_password(password) that returns True only if the password has at least 8 characters, at least one digit, and at least one uppercase letter.',
    learn: 'len(text) is the length. letter.isdigit() and letter.isupper() test one character. any(...) is True if any item passes:\n\nany(ch.isdigit() for ch in text)',
    starter: 'def strong_password(password):\n    pass\n',
    hints: ['You need three checks, and all three must be true.', 'return len(password) >= 8 and any(c.isdigit() for c in password) and any(c.isupper() for c in password)'],
    solution: 'def strong_password(password):\n    has_digit = any(c.isdigit() for c in password)\n    has_upper = any(c.isupper() for c in password)\n    return len(password) >= 8 and has_digit and has_upper\n',
    tests: [{ a: ['Hello123x'], e: true }, { a: ['hello'], e: false }, { a: ['ABCDEFG1'], e: true }, { a: ['abcdefg1'], e: false }, { a: ['Abcdefgh'], e: false }, { a: ['Ab1'], e: false }] },
  { id: 'se-brackets', level: 4, careers: ['software-engineer'], title: 'Balanced brackets', fn: 'balanced', sig: 'text',
    story: 'Code editors highlight a mistake when brackets do not match. You will build that check.',
    task: 'Write balanced(text) that returns True if every ( [ { has a matching closing bracket in the right order, and False otherwise. Ignore other characters.',
    learn: 'A stack (a list where you append and pop from the end) is last-in, first-out. Push opening brackets; when you see a closing bracket, the last opening one must match it.\n\nstack = []\nstack.append("(")\nstack.pop()',
    starter: 'def balanced(text):\n    stack = []\n    pairs = {")": "(", "]": "[", "}": "{"}\n    # go through each character\n    return len(stack) == 0\n',
    hints: ['Push openers: if ch in "([{": stack.append(ch).', 'For a closer: if the stack is empty or stack.pop() != pairs[ch], return False.'],
    solution: 'def balanced(text):\n    stack = []\n    pairs = {")": "(", "]": "[", "}": "{"}\n    for ch in text:\n        if ch in "([{":\n            stack.append(ch)\n        elif ch in pairs:\n            if len(stack) == 0 or stack.pop() != pairs[ch]:\n                return False\n    return len(stack) == 0\n',
    tests: [{ a: ['([])'], e: true }, { a: ['(]'], e: false }, { a: [''], e: true }, { a: ['(('], e: false }, { a: ['{[()]}'], e: true }, { a: [')('], e: false }] },

  // ---------- Financial Analyst ----------
  { id: 'fa-profit', level: 2, careers: ['financial-analyst'], title: 'Profit calculator', fn: 'profit', sig: 'revenue, costs',
    story: 'A small business owner asks you: "Did I make money this month?"',
    task: 'Write profit(revenue, costs) that returns revenue minus costs. A loss is a negative number.',
    learn: 'Subtraction uses -. Profit = revenue − costs.',
    starter: 'def profit(revenue, costs):\n    pass\n',
    hints: ['Subtract costs from revenue.', 'return revenue - costs'],
    solution: 'def profit(revenue, costs):\n    return revenue - costs\n',
    tests: [{ a: [500, 320], e: 180 }, { a: [100, 150], e: -50 }, { a: [0, 0], e: 0 }, { a: [1200, 1199], e: 1 }] },
  { id: 'fa-simple-interest', level: 3, careers: ['financial-analyst'], title: 'Simple interest', fn: 'simple_interest', sig: 'principal, rate_percent, years',
    story: 'A client wants to know how much a savings account earns without compounding.',
    task: 'Write simple_interest(principal, rate_percent, years) that returns principal × (rate_percent ÷ 100) × years.',
    learn: 'A rate of 5 percent is 5 / 100 = 0.05. Simple interest = principal × rate × time.',
    starter: 'def simple_interest(principal, rate_percent, years):\n    pass\n',
    hints: ['Convert the percent to a decimal by dividing by 100.', 'return principal * (rate_percent / 100) * years'],
    solution: 'def simple_interest(principal, rate_percent, years):\n    return principal * (rate_percent / 100) * years\n',
    tests: [{ a: [200, 5, 1], e: 10 }, { a: [1000, 3, 2], e: 60 }, { a: [0, 5, 3], e: 0 }, { a: [500, 4, 0], e: 0 }] },
  { id: 'fa-compound', level: 3, careers: ['financial-analyst'], title: 'Compound growth', fn: 'compound', sig: 'principal, rate_percent, years',
    story: 'Compound interest is why starting to save early matters. Show a client what $1,000 becomes.',
    task: 'Write compound(principal, rate_percent, years) that returns the final amount after the interest is added each year, rounded to 2 decimal places.',
    learn: 'Each year the amount is multiplied by (1 + rate/100). Powers use **:\n\n1000 * (1.10 ** 2)   # 1210.0\n\nround(x, 2) keeps 2 decimals.',
    starter: 'def compound(principal, rate_percent, years):\n    pass\n',
    hints: ['Growth factor = 1 + rate_percent / 100.', 'return round(principal * (1 + rate_percent / 100) ** years, 2)'],
    solution: 'def compound(principal, rate_percent, years):\n    return round(principal * (1 + rate_percent / 100) ** years, 2)\n',
    tests: [{ a: [1000, 10, 2], e: 1210 }, { a: [500, 5, 3], e: 578.81 }, { a: [100, 0, 5], e: 100 }, { a: [250, 8, 1], e: 270 }] },
  { id: 'fa-over-budget', level: 4, careers: ['financial-analyst'], title: 'Budget watchdog', fn: 'over_budget', sig: 'expenses, limit',
    story: 'A family gives you their spending by category. Flag the categories that went over the limit.',
    task: 'Write over_budget(expenses, limit). expenses is a dictionary like {"food": 120}. Return a list of the category names whose amount is greater than limit, sorted A to Z.',
    learn: 'Loop through a dictionary with items():\n\nfor name, amount in expenses.items():\n    ...\n\nsorted(list) returns a sorted copy.',
    starter: 'def over_budget(expenses, limit):\n    pass\n',
    hints: ['Loop through expenses.items() and collect names with amount > limit.', 'return sorted(result) at the end.'],
    solution: 'def over_budget(expenses, limit):\n    result = []\n    for name, amount in expenses.items():\n        if amount > limit:\n            result.append(name)\n    return sorted(result)\n',
    tests: [{ a: [{ food: 120, games: 40, books: 75 }, 70], e: ['books', 'food'] }, { a: [{ a: 5 }, 5], e: [] }, { a: [{}, 10], e: [] }, { a: [{ z: 9, y: 8 }, 1], e: ['y', 'z'] }] },

  // ---------- Mechanical Engineer ----------
  { id: 'me-force', level: 2, careers: ['mech-engineer'], title: 'Force on an object', fn: 'force', sig: 'mass, acceleration',
    story: 'Engineers use Newton\'s second law to size motors for robots.',
    task: 'Write force(mass, acceleration) that returns force in newtons (mass × acceleration).',
    learn: 'Newton\'s second law: F = m × a.',
    starter: 'def force(mass, acceleration):\n    pass\n',
    hints: ['Multiply mass by acceleration.', 'return mass * acceleration'],
    solution: 'def force(mass, acceleration):\n    return mass * acceleration\n',
    tests: [{ a: [2, 3], e: 6 }, { a: [10, 9.8], e: 98 }, { a: [0, 5], e: 0 }, { a: [1.5, 2], e: 3 }] },
  { id: 'me-mph', level: 3, careers: ['mech-engineer'], title: 'Unit conversion', fn: 'mph_to_ms', sig: 'mph',
    story: 'A test track reports speed in miles per hour, but your physics formulas need meters per second.',
    task: 'Write mph_to_ms(mph) that converts miles per hour to meters per second (multiply by 0.44704) and rounds to 2 decimal places.',
    learn: 'Unit conversion is multiplication by a constant. Always round at the end with round(value, 2).',
    starter: 'def mph_to_ms(mph):\n    pass\n',
    hints: ['Multiply by 0.44704.', 'return round(mph * 0.44704, 2)'],
    solution: 'def mph_to_ms(mph):\n    return round(mph * 0.44704, 2)\n',
    tests: [{ a: [60], e: 26.82 }, { a: [10], e: 4.47 }, { a: [0], e: 0 }, { a: [100], e: 44.7 }] },
  { id: 'me-kinetic', level: 3, careers: ['mech-engineer'], title: 'Kinetic energy', fn: 'kinetic_energy', sig: 'mass, velocity',
    story: 'How much energy must a crash barrier absorb? Start with kinetic energy.',
    task: 'Write kinetic_energy(mass, velocity) that returns 0.5 × mass × velocity².',
    learn: 'Use ** for powers: v ** 2 is v squared. Kinetic energy = ½ m v².',
    starter: 'def kinetic_energy(mass, velocity):\n    pass\n',
    hints: ['Square the velocity with velocity ** 2.', 'return 0.5 * mass * velocity ** 2'],
    solution: 'def kinetic_energy(mass, velocity):\n    return 0.5 * mass * velocity ** 2\n',
    tests: [{ a: [2, 3], e: 9 }, { a: [10, 0], e: 0 }, { a: [4, 5], e: 50 }, { a: [1, 10], e: 50 }] },
  { id: 'me-fall-time', level: 4, careers: ['mech-engineer'], title: 'Free-fall time', fn: 'fall_time', sig: 'height',
    story: 'A drone drops a package from a height. How long until it lands (ignoring air)?',
    task: 'Write fall_time(height) that returns the fall time in seconds, using t = √(2 × height ÷ 9.8), rounded to 2 decimals. Use import math at the top.',
    learn: 'math.sqrt(x) gives the square root, but you must write import math at the very top of your code.\n\nimport math\nmath.sqrt(16)   # 4.0',
    starter: 'import math\n\ndef fall_time(height):\n    pass\n',
    hints: ['Compute 2 * height / 9.8 first, then take math.sqrt of it.', 'return round(math.sqrt(2 * height / 9.8), 2)'],
    solution: 'import math\n\ndef fall_time(height):\n    return round(math.sqrt(2 * height / 9.8), 2)\n',
    tests: [{ a: [19.6], e: 2 }, { a: [0], e: 0 }, { a: [4.9], e: 1 }, { a: [100], e: 4.52 }] },

  // ---------- Environmental Scientist ----------
  { id: 'es-avg-temp', level: 2, careers: ['env-scientist'], title: 'Average temperature', fn: 'avg_temp', sig: 'temps',
    story: 'A weather station records the temperature every day. You report the weekly average.',
    task: 'Write avg_temp(temps) that returns the average of the list, rounded to 1 decimal place.',
    learn: 'average = sum(list) / len(list). round(value, 1) keeps one decimal.',
    starter: 'def avg_temp(temps):\n    pass\n',
    hints: ['Use sum() and len().', 'return round(sum(temps) / len(temps), 1)'],
    solution: 'def avg_temp(temps):\n    return round(sum(temps) / len(temps), 1)\n',
    tests: [{ a: [[20, 22, 24]], e: 22 }, { a: [[15.5, 16.5]], e: 16 }, { a: [[10]], e: 10 }, { a: [[1, 2, 2]], e: 1.7 }] },
  { id: 'es-hot-days', level: 3, careers: ['env-scientist'], title: 'Count the hot days', fn: 'hot_days', sig: 'temps, limit',
    story: 'Climate scientists track how many days go above a heat limit each summer.',
    task: 'Write hot_days(temps, limit) that returns how many temperatures in the list are strictly greater than limit.',
    learn: 'Use a counter in a loop:\n\ncount = 0\nfor t in temps:\n    if t > limit:\n        count = count + 1',
    starter: 'def hot_days(temps, limit):\n    pass\n',
    hints: ['Start a counter at 0 and add 1 when a temperature is above the limit.', 'for t in temps:\n    if t > limit:\n        count = count + 1'],
    solution: 'def hot_days(temps, limit):\n    count = 0\n    for t in temps:\n        if t > limit:\n            count = count + 1\n    return count\n',
    tests: [{ a: [[30, 25, 35, 31], 30], e: 2 }, { a: [[], 10], e: 0 }, { a: [[10, 10], 10], e: 0 }, { a: [[5, 6, 7], 0], e: 3 }] },
  { id: 'es-c-to-f', level: 3, careers: ['env-scientist'], title: 'Celsius to Fahrenheit', fn: 'c_to_f', sig: 'celsius',
    story: 'Your data is in Celsius but a partner lab in the U.S. wants Fahrenheit.',
    task: 'Write c_to_f(celsius) that returns Fahrenheit using F = C × 9 ÷ 5 + 32, rounded to 1 decimal place.',
    learn: 'Follow the order of operations: multiply and divide first, then add 32. round(value, 1) rounds.',
    starter: 'def c_to_f(celsius):\n    pass\n',
    hints: ['Multiply by 9, divide by 5, then add 32.', 'return round(celsius * 9 / 5 + 32, 1)'],
    solution: 'def c_to_f(celsius):\n    return round(celsius * 9 / 5 + 32, 1)\n',
    tests: [{ a: [100], e: 212 }, { a: [0], e: 32 }, { a: [-40], e: -40 }, { a: [37], e: 98.6 }] },
  { id: 'es-biggest-jump', level: 4, careers: ['env-scientist'], title: 'Biggest daily change', fn: 'biggest_jump', sig: 'readings',
    story: 'A sudden jump in river temperature can harm fish. Find the biggest one-day change.',
    task: 'Write biggest_jump(readings) that returns the largest difference (ignoring sign) between two neighboring readings. If there are fewer than 2 readings, return 0.',
    learn: 'abs(x) removes the minus sign. Loop with an index to compare each reading to the next:\n\nfor i in range(len(readings) - 1):\n    diff = abs(readings[i + 1] - readings[i])',
    starter: 'def biggest_jump(readings):\n    best = 0\n    # compare neighbors\n    return best\n',
    hints: ['Loop i from 0 to len(readings) - 2 and compare readings[i] with readings[i + 1].', 'Keep the biggest difference in best.'],
    solution: 'def biggest_jump(readings):\n    best = 0\n    for i in range(len(readings) - 1):\n        diff = abs(readings[i + 1] - readings[i])\n        if diff > best:\n            best = diff\n    return best\n',
    tests: [{ a: [[10, 12, 9, 15]], e: 6 }, { a: [[5]], e: 0 }, { a: [[3, 3, 3]], e: 0 }, { a: [[1, 10]], e: 9 }, { a: [[]], e: 0 }] },
];
