// Mini-lessons shown before any practice. Three tiers per subject:
// tier 1 = levels 1-2, tier 2 = level 3, tier 3 = levels 4-5. Each lesson is followed by a 3-question check.
window.PF_LESSONS = {
  math: [
    { title: 'Adding big numbers and finding percents',
      body: ['To add two-digit numbers, add the ones first, then the tens. If the ones add up to 10 or more, carry 1 to the tens column.',
        'A percent means "out of 100". To find 25% of 80, turn 25% into 25 ÷ 100 = 0.25, then multiply: 0.25 × 80 = 20. Handy shortcuts: 50% is half, 25% is a quarter, and 10% means divide by 10.'],
      example: '47 + 38\nones: 7 + 8 = 15 → write 5, carry 1\ntens: 4 + 3 + 1 = 8\nanswer: 85\n\n10% of 360 = 36, so 20% of 360 = 72',
      points: ['Line up the ones and the tens', 'Percent = out of 100', '10% of a number: move the decimal point one place left'] },
    { title: 'Solving equations for x',
      body: ['An equation says two sides are equal. To solve for x, undo what was done to x, in reverse order. Whatever you do to one side, you must do to the other side.',
        'Undo adding or subtracting first, then undo multiplying or dividing.'],
      example: '3x + 5 = 20\nsubtract 5 from both sides: 3x = 15\ndivide both sides by 3: x = 5\ncheck: 3(5) + 5 = 20 ✓',
      points: ['Undo + and − first, then × and ÷', 'Do the same thing to both sides', 'Always check by putting your answer back in'] },
    { title: 'Quadratics and number tricks',
      body: ['A quadratic like x² − 7x + 12 = 0 can often be factored. Find two numbers that multiply to 12 and add to −7: that is −3 and −4. So (x − 3)(x − 4) = 0, which means x = 3 or x = 4.',
        'Number tricks: 1 + 2 + … + n = n(n + 1) ÷ 2 (pair the ends). The divisors of n come in pairs that multiply to n. The least common multiple of a and b is a × b ÷ gcd(a, b). Remainders repeat in cycles: powers of 2 divided by 7 leave 2, 4, 1, 2, 4, 1…'],
      example: '1 + 2 + … + 20 = 20 × 21 ÷ 2 = 210\ndivisors of 12: 1, 2, 3, 4, 6, 12 → 6 divisors\nLCM(12, 18) = 12 × 18 ÷ 6 = 36',
      points: ['Factor: find two numbers that multiply to c and add to b', 'Look for pairs and cycles', 'Test small cases to spot a pattern'] },
  ],
  stats: [
    { title: 'Mean, median and range',
      body: ['The mean (average) is the sum of all values divided by how many there are. The median is the middle value after sorting; with an even number of values, it is the average of the two middle ones. The range is the biggest value minus the smallest.'],
      example: 'data: 4, 9, 2, 7, 8\nmean = (4 + 9 + 2 + 7 + 8) ÷ 5 = 6\nsorted: 2, 4, 7, 8, 9 → median = 7\nrange = 9 − 2 = 7',
      points: ['Mean = total ÷ count', 'Sort before finding the median', 'Range = max − min'] },
    { title: 'Probability basics',
      body: ['Probability tells how likely something is: favorable outcomes ÷ total outcomes. It is always between 0 (impossible) and 1 (certain). Simplify your fraction at the end.',
        'For a fair die, each of the 6 sides is equally likely.'],
      example: 'roll a die, P(more than 4): the sides 5 and 6 work → 2/6 = 1/3\nbag with 3 red and 4 blue marbles: P(red) = 3/7',
      points: ['Probability = favorable ÷ total', 'Count the total carefully (red + blue, not just red)', 'Simplify fractions'] },
    { title: 'Counting, expected value and no-replacement draws',
      body: ['To count ways to choose k items from n, multiply n × (n−1) × … for k terms and divide by k!. Choosing 2 from 6: (6 × 5) ÷ 2 = 15.',
        'When you draw without replacing, the totals shrink. Both marbles red from 4 red + 3 blue: (4/7) × (3/6) = 2/7. Expected value is the average result over many tries: add up each value × its probability.'],
      example: '3 coins have 8 equal outcomes (HHH, HHT, …). Exactly 2 heads: HHT, HTH, THH → 3 of 8.\nWin $20 with chance 1/2, else $0 → expected value = 20 × 1/2 = $10',
      points: ['Choosing is order-free, so divide out the repeats', 'No replacement: both the top and bottom shrink', 'Expected value = Σ value × probability'] },
  ],
  logic: [
    { title: 'Number patterns: add or multiply',
      body: ['To find the next number, look for the rule. If the gap between neighbors is always the same, the rule is "add that gap". If each number is the previous one times the same factor, the rule is "multiply".'],
      example: '3, 7, 11, 15, ?  → gaps are all 4 → next is 19\n2, 6, 18, 54, ? → each is ×3 → next is 162',
      points: ['Check the differences first', 'Then check the ratios (divide neighbors)', 'Test your rule on every pair'] },
    { title: 'Patterns that build on themselves',
      body: ['In a Fibonacci-style pattern, every number is the sum of the two numbers before it. If the gaps are not constant and the numbers are not multiplied by a fixed factor, test whether each term equals the sum of the previous two.'],
      example: '2, 3, 5, 8, 13, ?  → 5 + 8 = 13 → next is 8 + 13 = 21',
      points: ['Check: is each term the sum of the two before it?', 'Write the rule in words', 'Check it works for the whole list'] },
    { title: 'Squares, primes and growing gaps',
      body: ['Square numbers: 1, 4, 9, 16, 25, 36… (n × n). Prime numbers: 2, 3, 5, 7, 11, 13, 17, 19… (only divisible by 1 and themselves).',
        'If the gaps themselves change in a pattern (like +2, +3, +4), keep track of the gaps and extend them.'],
      example: '4, 9, 16, 25, ? → squares of 2, 3, 4, 5 → next is 6² = 36\n1, 3, 6, 10, ? → gaps are 2, 3, 4 → next gap is 5 → 15',
      points: ['Memorize the first squares and primes', 'Look at the gaps of the gaps', 'Build a table'] },
  ],
  coding: [
    { title: 'Python first steps: print, math, loops and strings',
      body: ['Python follows math order of operations: multiplication happens before addition, so 2 + 3 * 4 is 14, not 20. Text is called a string and goes in quotes, like "hello". A for loop repeats code once for every item.',
        'print() shows a value on the screen.'],
      example: 'print(2 + 3 * 4)        # 14\nname = "Maya"           # a string\nfor i in range(3):\n    print(i)            # 0, 1, 2',
      points: ['Order of operations works like math class', 'Strings use quotes', 'for repeats code for each item'] },
    { title: 'Lists, comparing and integer division',
      body: ['A list holds many values: nums = [4, 7, 9]. len(nums) tells you how many (3). A single = stores a value in a variable, while a double == asks "are these equal?".',
        '// is integer division (it drops the remainder): 17 // 5 is 3. % gives the remainder: 17 % 5 is 2.'],
      example: 'nums = [4, 7, 9]\nprint(len(nums))      # 3\nprint(nums[0])        # 4 (counting starts at 0)\nprint(17 // 5, 17 % 5)  # 3 2',
      points: ['= stores, == compares', 'Lists start counting at 0', '// divides without the remainder; % gives the remainder'] },
    { title: 'How programmers think: algorithms and efficiency',
      body: ['Binary search finds an item in a sorted list by checking the middle and throwing away half each time. Searching 1,024 items takes at most about 10 checks (because 2¹⁰ = 1024). A stack is "last in, first out", like a pile of plates.',
        'Big-O describes how work grows with input size. Looping once over n items is O(n); checking one item is O(1); two nested loops is O(n²).'],
      example: 'sorted list, find 7: check the middle → too big? keep the left half; too small? keep the right half.\nstack: push A, push B, pop → B comes out first.',
      points: ['Binary search halves the work each step', 'Stack = last in, first out', 'One loop over n items is O(n)'] },
  ],
  science: [
    { title: 'Cells, plants and the solar system',
      body: ['Mitochondria are the "powerhouses" of the cell: they turn food into usable energy. Plants take in carbon dioxide (CO₂) and, using sunlight, make sugar and release oxygen. This is photosynthesis.',
        'Mercury is the planet closest to the Sun, followed by Venus, Earth and Mars.'],
      example: 'photosynthesis: carbon dioxide + water + light → sugar + oxygen',
      points: ['Mitochondria = energy', 'Plants take in CO₂', 'Order from the Sun: Mercury, Venus, Earth, Mars'] },
    { title: 'Forces, acids and DNA',
      body: ['Force is measured in newtons (N). The pH scale runs from 0 to 14: below 7 is acidic, 7 is neutral, above 7 is basic. DNA, the instruction book of life, is shaped like a twisted ladder called a double helix.'],
      example: 'lemon juice: pH ≈ 2 → acidic\nwater: pH 7 → neutral\nsoap: pH ≈ 10 → basic',
      points: ['Force → newtons', 'pH < 7 acidic, pH > 7 basic', 'DNA = double helix'] },
    { title: 'F = ma, organs and ecosystems',
      body: ['Newton\'s second law: force = mass × acceleration. A 2 kg object accelerating at 3 m/s² needs 2 × 3 = 6 newtons.',
        'The pancreas makes insulin, which helps your cells use sugar. In an ecosystem, producers (like plants) make their own food; consumers eat other organisms; decomposers break down dead matter.'],
      example: 'F = m × a = 2 kg × 3 m/s² = 6 N',
      points: ['F = m × a', 'Pancreas → insulin', 'Producers make their own food'] },
  ],
  writing: [
    { title: 'Complete sentences and word choice',
      body: ['A complete sentence has a subject (who or what) and a verb (the action), and it makes sense by itself. "The cat slept on the mat." is complete; "Because it rained." is not.',
        'Watch the look-alikes: they\'re = they are, their = belongs to them, there = a place. Synonyms are words with almost the same meaning (rapid ≈ fast).'],
      example: 'They\'re going to their house over there.',
      points: ['Subject + verb = a sentence', 'they\'re = they are', 'A synonym means almost the same'] },
    { title: 'Adverbs, its/it\'s and thesis statements',
      body: ['An adverb describes a verb, and many end in -ly: "She quickly solved it." its (no apostrophe) shows ownership; it\'s means "it is".',
        'A thesis statement is the main argument of an essay, usually at the end of the first paragraph. Everything else in the essay supports it.'],
      example: 'The dog wagged its tail because it\'s happy.\nThesis: School should start later because teens need more sleep.',
      points: ['Adverb = describes how', 'it\'s = it is; its = belongs to it', 'Thesis = the main claim'] },
    { title: 'Style: semicolons, fallacies and active voice',
      body: ['A semicolon joins two complete sentences that are closely related: "I studied hard; I passed the test." A fallacy is a flaw in an argument, like the bandwagon fallacy ("everyone is doing it, so it must be right").',
        'In active voice the subject does the action ("The team won the game"). In passive voice the action happens to the subject ("The game was won by the team"). Active is usually clearer.'],
      example: 'Active: The student wrote the essay.\nPassive: The essay was written by the student.',
      points: ['Semicolon: two complete sentences', 'Bandwagon = popularity is not proof', 'Prefer active voice'] },
  ],
  economics: [
    { title: 'Supply, demand, revenue and saving',
      body: ['When many people want something (demand goes up) and there is the same amount available (supply stays the same), the price usually rises. Revenue is the money a business earns from its sales. Saving means setting money aside: $15 a week for 8 weeks is 15 × 8 = $120.'],
      example: 'sells 40 cups at $2 each → revenue = 40 × 2 = $80',
      points: ['Demand up + same supply → price up', 'Revenue = money from sales', 'Saving = amount × number of weeks'] },
    { title: 'Profit, opportunity cost and simple interest',
      body: ['Profit = revenue − costs. Opportunity cost is the value of the next-best thing you give up when you choose. Simple interest is calculated only on the original amount: interest = principal × rate × time.'],
      example: 'revenue $100 − costs $60 = profit $40\n$200 at 5% for 1 year: 200 × 0.05 × 1 = $10',
      points: ['Profit = revenue − costs', 'Opportunity cost = the best alternative given up', 'Simple interest = P × r × t'] },
    { title: 'Compound interest, inflation and margins',
      body: ['With compound interest you earn interest on your interest. $1,000 at 10% per year becomes $1,100 after year 1 and $1,210 after year 2 (10% of $1,100 is $110). Inflation is when prices in general rise over time, so money buys less. Profit margin = profit ÷ revenue.'],
      example: 'revenue $50k, costs $40k → profit $10k → margin = 10 ÷ 50 = 20%',
      points: ['Compound: multiply by (1 + rate) each period', 'Inflation = rising prices', 'Margin = profit ÷ revenue'] },
  ],
  people: [
    { title: 'Listening, empathy and feedback',
      body: ['Active listening means giving your full attention and repeating back what you heard. Empathy is understanding how someone else feels. Good feedback is specific and kind, and it is about the work, not the person.'],
      example: '"So you felt left out when they started without you. Is that right?"',
      points: ['Repeat back what you heard', 'Empathy = understand their feelings', 'Specific and kind feedback'] },
    { title: 'Questions, body language and needs',
      body: ['Open-ended questions can\'t be answered with just yes or no ("How did you feel about the game?"). Body language (posture, face, gestures) is nonverbal communication. Maslow\'s hierarchy says people need basics like food and sleep first, before things like friendship and achievement.'],
      example: 'Closed: "Did you win?" Open: "What was the best part of the game?"',
      points: ['Open questions start with how or what', 'Body language = nonverbal', 'Basic needs come first'] },
    { title: 'Bias, experiments and the placebo effect',
      body: ['Confirmation bias is favoring information that matches what you already believe. In an experiment, the control group gets no treatment so you have something to compare to. The placebo effect is when people feel better because they expect a treatment to work, even if it does nothing.'],
      example: 'Test a study app: one group uses it (test group); the control group studies normally.',
      points: ['Confirmation bias: noticing only what fits your belief', 'Control group = comparison', 'Placebo = belief creates real effects'] },
  ],
  design: [
    { title: 'Color, vectors and white space',
      body: ['The traditional primary colors are red, yellow and blue; you mix them to get the rest. A vector image (like SVG) is made of shapes and math, so it stays sharp at any size. White space is the empty space that helps design breathe and be readable.'],
      example: 'Logos are usually vectors so they look sharp on a tiny icon and a huge billboard.',
      points: ['Primary: red, yellow, blue', 'Vector = scales without blur', 'White space helps readability'] },
    { title: 'Complementary colors, thirds and kerning',
      body: ['Complementary colors sit opposite each other on the color wheel (blue and orange, red and green) and look vivid together. The rule of thirds divides an image into a 3×3 grid; placing the subject on the lines feels balanced. Kerning is adjusting the space between letters.'],
      example: 'Blue + orange = high contrast. Put the subject at a grid intersection.',
      points: ['Opposite on the wheel = complementary', 'Rule of thirds = 3×3 grid', 'Kerning = space between letters'] },
    { title: 'Contrast, grouping and personas',
      body: ['Accessible text needs enough contrast: the standard (WCAG AA) is at least 4.5 : 1 for normal text. Gestalt "proximity" means things placed close together are seen as a group. A persona is a fictional profile of a typical user, used to design for real needs.'],
      example: 'Light gray text on white fails contrast. Group a button with its label by putting them close together.',
      points: ['Contrast ratio ≥ 4.5 : 1', 'Proximity groups things', 'Persona = typical user profile'] },
  ],
  civics: [
    { title: 'Branches of government and the Bill of Rights',
      body: ['The U.S. federal government has three branches: legislative (Congress makes laws), executive (the President carries out laws) and judicial (courts interpret laws). The first ten amendments to the Constitution are called the Bill of Rights.'],
      example: 'make laws → Congress; carry out laws → President; interpret laws → courts',
      points: ['3 branches', 'Legislative = makes laws', 'Bill of Rights = first 10 amendments'] },
    { title: 'Free speech, judicial review and juries',
      body: ['The First Amendment protects freedom of speech, religion, press, assembly and petition. Judicial review is the power of courts to strike down laws that break the Constitution. In a criminal trial, a jury (or sometimes the judge) decides guilty or not guilty.'],
      example: 'A court rules a law unconstitutional → the law can no longer be enforced.',
      points: ['First Amendment = speech and more', 'Judicial review = courts check laws', 'Jury decides the verdict'] },
    { title: 'Precedent, burden of proof and Marbury v. Madison',
      body: ['Precedent means courts follow earlier decisions on similar cases. In a criminal case, the prosecution must prove guilt "beyond a reasonable doubt", the highest standard. Marbury v. Madison (1803) established judicial review.'],
      example: 'Before deciding, a judge looks for earlier cases with similar facts (precedent).',
      points: ['Precedent = earlier decisions guide new ones', 'Criminal burden: beyond a reasonable doubt', 'Marbury v. Madison → judicial review'] },
  ],
};
